GoogleCloudPlatform/fda-mystudies

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp

Issue #1259 fixed.
Changed class from `col-md-3` to `col-md-4`.

[Study Builder]Issue #1259 fixes, Alignment issue

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/AuditLogDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/RequestWrapper.java
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/loginPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/js/jquery.password-validator.js

- Fixed issue  #2497 Study builder > Password criteria text change. 
- Updated the error messages to be consistent "Please complete this field." as per issue #955.
- Changes in AuditLogDAOImpl.java, RequestWrapper.java because of (source Format  + Organize import).

Fixed issue #2497 Study builder > Password criteria text change 

---

common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/model/StudyAppDetails.java
common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/model/StudyInfo.java
common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/repository/StudyRepository.java
participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/mapper/ParticipantMapper.java
participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/StudyServiceImpl.java
participant-manager-datastore/participant-manager-service/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/StudyControllerTest.java

To fix the issue #1802, added `studyStatus` attribute.

Participant Manager : Fixed issue #1802

---

participant-manager/src/app/error/error.component.html
participant-manager/src/app/page-not-found/page-not-found.component.html
participant-manager/src/assets/css/root.scss

#2304 error and page not found icon changed

#2304 error and page not found icon changed

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/addOrEditUserPage.jsp

Disable 'Re-send activation link' when viewing the users record in view mode . Issue #2681 fix

[Study Builder] Disable 'Re-send activation link' for view mode

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewSettingAndAdmins.jsp

Modified `viewSettingAndAdmins.jsp`

[Study Builder] Fixed issue #2713

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyList.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/css/theme.css

[SB] Manage Studies screen issue is fixed#2745

[SB] Manage Studies screen issue is fixed#2745

---

Android/app/src/main/java/com/harvard/studyappmodule/SurveyActivitiesListAdapter.java
Android/app/src/main/res/values/strings.xml

grayed out activities that's not available yet
added msg for grayed out activities

Android - fixes for #2721

---

participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/SiteServiceImpl.java

Fixed issue #2705
Sorted by site name in alphabetical order

Participant Manager : Fixed issue #2705, in GET /sites API

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionQuestion.jsp

Issue #2752 fixed.
Disable delete icon if there are minimum 2 answer options in comprehension test.

[Study Builder]Issue #2752 fixed, [SB] Add Comprehension test question > User should not be able to delete any option when there are only 2 options

---

iOS/MyStudies/MyStudies/Controllers/EligibilityUI/InEligibilityStepViewController.swift
iOS/MyStudies/MyStudies/Controllers/StudyUI/StudyOverviewUI/StudyHomeViewController.swift

related issue #2472 fix for iOS.

Update status back to yetToEnroll from inEligible if eligible.

---

iOS/MyStudies/MyStudies/Controllers/StudyUI/ResourceUI/ResourceDetailViewController.swift
iOS/MyStudies/MyStudies/Storyboards/Study.storyboard

fixes #2789 also fixes an issue with HTML resources breaking the text.

iOS - Dashboard study status fixes.

---

Android/app/src/main/java/com/harvard/studyappmodule/SurveyActivitiesFragment.java
Android/app/src/main/java/com/harvard/studyappmodule/SurveyCompleteActivity.java

added siteId for updateStudyState api

Android - #2772

---

Android/app/src/main/java/com/harvard/WebViewActivity.java
Android/app/src/main/java/com/harvard/studyappmodule/ResourcesWebViewActivity.java
Android/app/src/main/java/com/harvard/studyappmodule/consent/consentsharingstepcustom/LoadMoreActivity.java

webview for android 10 updated

Android - webview android 10

---

Android/app/src/main/res/layout/fragment_survey_dashboard.xml

UI adjustment in title for dashboard

Android - UI fix

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/fdaAdminDashBoardPage.jsp

Study Builder : Fixed Account Management and added dropdown as mentioned in issue #958

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp

Issue #1259 fixed
Remove `requiredStar `class from description.

[Study Builder]Issue #1259 fixes, remove requiredStar class from description

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditResourcePage.jsp

Issue #2754 and #2755 fixed.
Converting summernote to html before saving .

[Study Builder]Issue #2754 and #2755 fixes, Hyperlinks added in Resource text field is not Saved and Issue in Resource text field

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/errorPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/fdaAdminDashBoardPage.jsp

Study Builder : Fixed UI issue #958 and #2304

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp

Issue #2785 fixed
- Changed `displayTextChoiceText0 `to `displayTextChoiceText1`
- Added `$(".remBtnDis").css("pointer-events", "auto");` and `$(".remBtnDis").css("pointer-events", "none");` based on scenarios.

[Study Builder]Issue #2785 fixed, [SB] Add questionnaire > Form step > Text choice > Response level attributes > issues

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/basicInformation.jsp

Issue #2362 fixes
Emptying `$('#thumbnailImageId').val("")`; when user upload image directly.

[Study Builer]Issue 2362, Thumbnail image uploaded is not saving

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/actionListPage.jsp
study-builder/fdahpStudyDesigner/src/test/java/com/fdahpstudydesigner/controller/StudyControllerTest.java

Fixed issue #2805: 
- Disabled Publish updates button when all study sections are not marked as completed
- removed `shouldUpdateStudyAction()` test as publish as upcoming study functionality will not be there

[study builder] Fixed issue 2805

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java

Issue #2832 fixed - Consent section is getting mark as completed automatically

[SB] Issue #2832 fixes, Create study/Edit study > Consent section is getting mark as completed automatically

---

participant-manager/src/app/site-coordinator/sites/site-details/site-details.component.ts
participant-manager/src/app/site-coordinator/studies/update-target/update-target.component.html

1. Issue #2804 recalled api of site decommission  
2. Issue #2684 fixed

Pm web app issues 2804 and 2684 fixed

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp

Study Builder: Fixed issue #2844 Questionnaires > Daily > Unable to enter date or time fields manually

---

participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/common/UserMgmntEvent.java

Fixed Issue #2571,
Corrected description and event code for `REGISTRATION_SUCCEEDED` event.

[participant-datastore] : Fixed Issue #2571, Events are not triggered for Mobile apps in User Management bundle

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp

[SB][Dev][UI] adjusted the UI for time Picker in Activities Screen #2342 and adjusted colour and opacity everywhere while adding time picker

[SB][Dev][UI] adjusted the UI for time Picker in Activities Screen #2342

---

participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/UserProfileController.java
participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/VerifyEmailIdController.java
participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/service/UserRegistrationServiceImpl.java
participant-datastore/user-mgmt-module/user-mgmt/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/UserRegistrationControllerTest.java
participant-datastore/user-mgmt-module/user-mgmt/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/VerifyEmailIdControllerTest.java

Participant Datastore: Fixed issue #2867  #2880

---

study-datastore/src/main/java/com/hphc/mystudies/dao/ActivityMetaDataDao.java

[Study Datastore] /activityList [GET] endpoint start time empty issue #2894  fix

[Study Datastore] /activityList [GET] endpoint starttime empty issue fix

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/common/StudyBuilderAuditEvent.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/NotificationDAOImpl.java

Study level resend notification is not triggered. Issue #2872 fix

[Study Builder] Study level resend notification is not triggered

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyQuestionnaireDAOImpl.java

Questionnaires not displayed when viewed from last published version. Issue #2842 fix

[Study Builder]Questionnaires not displayed when viewed from last published version

---

study-datastore/src/main/java/com/hphc/mystudies/service/StudyMetaDataService.java

[SB] Overview > Default image in overview screens is not working in a scenario #2857 issue fix

[SB] Overview > issue #2857 fix

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/myAccount.jsp

Displaying view only permission even though user is doesn't have any permission. Issue #2884 fix

[Study Builder]Displaying view only permission even though user is doesn't have any permission

---

study-datastore/src/main/java/com/hphc/mystudies/dao/AppMetaDataDao.java

Wrongly displayed scheduled notifications in mobile app . Issue #2881 fix

[Study Builder]Wrongly displayed scheduled notifications in mobile app

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentInfoList.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp

Issue #2886 fixed - [SB] Comprehension test > 'Mark as completed' tick mark issue

[SB]Issue 2886 fix, Comprehension test > 'Mark as completed' tick mark issue 

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/NotificationServiceImpl.java
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/notification/createOrUpdateNotification.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp

Study Builder: Fixed issue #2888 #2907 #2957

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/myAccount.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp

Study Builder :Fixed Issue #2945 and #2928

Study Builder :Fixed Issue #2945 and #2928

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
study-builder/fdahpStudyDesigner/src/main/resources/messageResource.properties
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionList.jsp

Study Builder : Fixed issue #2914, Eligibility Test and Consent Sections > Correct the messages displayed on click of Done

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp

Numeric response type>Minimum value 0 and Maximum value 10000 into these fields are set as default for Questionstep and form step in questinnaries.
Text scale>UI issue fixed in edit questionnaire page

[Study Builder] issue #2866 #2959 fixes

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/actionListPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskListPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditResourcePage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditStudyActiveTask.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditStudyNotification.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/basicInformation.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionList.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionQuestion.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentInfo.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentInfoList.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentReviewAndEConsentPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/formStep.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/instructionsStep.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/overViewPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionaryListPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/resourceListPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyEligibilty.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyEligibiltyTest.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyNotificationList.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewFetalStudyActiveTask.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewSettingAndAdmins.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewSpatialStudyActiveTask.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewTowerStudyActiveTask.jsp

Study Builder: Fixed issue #2903

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp

Questionnaire's scale type app should not allow to set default value less than minimum value. Issue #2967 fix

[Study Builder] Questionnarie's Scale  App should not allow to set default value less than minimum value

---

iOS/MyStudies/MyStudies/Controllers/StudyUI/ActivityUI/ActivitiesViewController.swift
iOS/MyStudies/MyStudies/Networking/APIs/ResponseServices.swift
iOS/MyStudies/MyStudies/Views/Cells/CollectionView/Study/StudyDashboardStatisticsCollectionViewCell.swift

Resolved #2900 
Resolved #2843

iOS - Stats fixes

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp

[Study Builder] Questionnaires > Add questionnaire > Text scale response type > Wrong radio button is selected in response level attributes #2978 #2959 fixes
Text scale response type implemented of saving

[Study Builder] Questionnaires > Add questionnaire > Text scale response #2978 #2959 fixes

---

participant-datastore/enroll-mgmt-module/enroll-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/service/StudyStateServiceImpl.java
participant-datastore/enroll-mgmt-module/enroll-mgmt/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/tests/StudyStateControllerTest.java

This PR contains the issue fixes for issue #2562 .
For this issue fixes 
Module: Enroll(Participant Datastore) `STUDY_STATE_SAVED_OR_UPDATED_FOR_PARTICIPANT`  audit log event is corrected for `participantId` .

[Participant-Datastore]: Issue 2562 fixes

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
study-builder/fdahpStudyDesigner/src/test/java/com/fdahpstudydesigner/common/PathMappingUri.java
study-builder/fdahpStudyDesigner/src/test/java/com/fdahpstudydesigner/controller/StudyControllerTest.java

This PR contains the issue fixes for issue #2834 
For this issue fixes, `NEW_STUDY_CREATION_INITIATED`  audit log event is captured in `/adminStudies/viewBasicInfo.do` end point .

[Study Builder]: Issue 2834 fixes

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyQuestionnaireController.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyQuestionnaireDAO.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyQuestionnaireDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyQuestionnaireService.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyQuestionnaireServiceImpl.java

Study Builder : Fixed issue #2603, Corrected Study Version for Audit Log Events

---

Android/app/src/main/java/com/harvard/studyappmodule/SurveyActivitiesFragment.java
Android/app/src/main/java/com/harvard/studyappmodule/SurveyCompleteActivity.java

added participantId for updateStudyState api for issue #2562

Android - issue #2562

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/addOrEditUserPage.jsp

Issue #2893 fixed - Users > Assign permissions section should be disabled in view only mode.

[Study Builder]Issue #2893 fixed, Users > Assign permissions section should be disabled in view only mode

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp

Issue #2946 fixed- Questionnaires > Branching > Destination step should not be mandatory for "other' option in text choice questions

[Study Builder]Issue #2946 fixed, Questionnaires > Branching > Destination step should not be mandatory for "other' option in text choice questions 

---

participant-datastore/enroll-mgmt-module/enroll-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/EnrollmentTokenController.java
participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/AppServiceImpl.java
participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/ConsentServiceImpl.java
participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/SiteServiceImpl.java
participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/StudyServiceImpl.java
participant-manager-datastore/participant-manager-service/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/ConsentControllerTest.java
participant-manager-datastore/participant-manager-service/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/InviteParticipantTaskScheduledTest.java
participant-manager-datastore/participant-manager-service/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/SiteControllerTest.java
participant-manager-datastore/participant-manager-service/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/StudyControllerTest.java

Participant Manager Datastore: Fixed issue #3005 #3006 #3007

---

auth-server/oauth-scim-service/src/main/java/com/google/cloud/healthcare/fdamystudies/oauthscim/controller/UserController.java
auth-server/oauth-scim-service/src/main/java/com/google/cloud/healthcare/fdamystudies/oauthscim/service/UserServiceImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerConstants.java

Fixed issue #2997 : Replaced text in `FdahpStudyDesignerConstants`
#2989: Set `userId `in `auditRequest `object

[Study Builder, Auth Server]Fixed issue #2997 #2989

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/myAccount.jsp

My account screen permission section issue #3017  fix

[Study Builder]My account screen permission section issue fix

---

iOS/MyStudies/MyStudies/Controllers/GatewayUI/ConfirmationViewUI/ConfirmationViewController.swift
iOS/MyStudies/MyStudies/Models/UserModel/User.swift
iOS/MyStudies/MyStudies/Networking/APIs/EnrollServices.swift
iOS/MyStudies/MyStudies/Networking/APIs/UserServices.swift

Send join study details with account deletion.

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/myAccount.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp

Study Builder: Fixed issue #562 #3030

---

iOS/MyStudies/MyStudies/AppDelegate.swift
iOS/MyStudies/MyStudies/Controllers/SplashViewController.swift
iOS/MyStudies/MyStudies/Networking/Services/SessionService.swift
iOS/MyStudies/MyStudies/Utils/Helpers/Managers/LocalNotification.swift

Fix resource notification navigation and crash.

---

iOS/MyStudies/MyStudies/Controllers/StudyUI/ResourceUI/ResourceDetailViewController.swift

Reload webview with downloaded resource.

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyQuestionnaireDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/myAccount.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/overViewPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/addOrEditUserPage.jsp

Study Builder : Fixed issue #2929 and #2603, Text Changes and study version correction for Audit Log Event

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/notification/createOrUpdateNotification.jsp

Study Builder: Fixed issue #3058

---

participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/LocationServiceImpl.java

Participant Manager : Fixed issue #3036

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionList.jsp

Study Builder: Fixed issue #3055

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/notification/notificationListPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionList.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyNotificationList.jsp

Study Builder : Fixed issue #3054, Questions table issues and #3051, Remove tooltip when user mouse hovered on the data

---

participant-datastore/enroll-mgmt-module/enroll-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/dao/ParticipantStudiesInfoDaoImpl.java
participant-datastore/enroll-mgmt-module/enroll-mgmt/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/tests/StudyStateControllerTest.java

Multiple record for same study in studyState endpoint issue #3071 fix

[Participant Enroll Datastore] Multiple record for same study in /studyState endpoint issue fix

---

iOS/MyStudies/MyStudies/AppDelegate.swift
iOS/MyStudies/MyStudies/Controllers/GatewayUI/ProfileViewUI/ProfileViewController.swift
iOS/MyStudies/MyStudies/Controllers/GatewayUI/SlideMenu/LeftMenuViewController.swift

Update push token to an empty string before logout.

---

iOS/MyStudies/MyStudies/Views/Steps/CustomIntructionStep/CustomInstructionStepViewController.swift

Decode rich text for regex condition in instruction step.

---

iOS/MyStudies/MyStudies/Controllers/GatewayUI/NotificationUI/NotificationViewController.swift
iOS/MyStudies/MyStudies/Models/UserModel/User.swift
iOS/MyStudies/MyStudies/Utils/Resources/Plists/UI/FilterData.plist

This includes some text changes and fixes #3070

iOS - UI fixes and text changes.

---

iOS/MyStudies/MyStudies/Models/Activity/Activity.swift
iOS/MyStudies/MyStudies/Models/Database/DBHandler.swift

Fix schedule for launch with study response type AD activity.

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp

Study Builder: Fixed issue #562

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/templates/copyright.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/fdaAdminDashBoardPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/loginPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/notification/notificationListPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyList.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/userListPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/css/style.css

Study Builder: Fixed #3049 #3050

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionQuestion.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp

Study Builder: Fixed issue #2919

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/myAccount.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/notification/notificationListPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/actionListPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskListPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/basicInformation.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionList.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionQuestion.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentInfoList.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentReviewAndEConsentPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/formStep.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/overViewPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionaryListPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/resourceListPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyEligibilty.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyList.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyNotificationList.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/addOrEditUserPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/userListPage.jsp

Study Builder : Fixed issue #2929, Revise text across screens

---

Android/app/src/main/res/values/strings.xml

Android - minor text changes

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentReviewAndEConsentPage.jsp

This PR contains the issue fixes for issue #3060 
Auto-created consent document title font size is reduced to 15px.

[Study Builder]: Issue 3060 fixes

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyQuestionnaireController.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyQuestionnaireDAO.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyQuestionnaireDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyQuestionnaireService.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyQuestionnaireServiceImpl.java
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/formStep.jsp
study-builder/fdahpStudyDesigner/src/test/java/com/fdahpstudydesigner/controller/StudyQuestionnaireControllerTest.java
study-builder/fdahpStudyDesigner/src/test/resources/import.sql

This PR contains the issue fixes for issue #3040 
For this issue fixes: 
Value for `${questionnaire_id}` , `${step_id}` , and `${form_id}` in description for event `STUDY_QUESTION_STEP_IN_FORM_DELETED  `is corrected with **short title** key value.

[Study Builder]: Issue 3040 fixes

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp

issue #3120 fixed -Unable to create 'Tower of Hanoi' active task with Custom schedule

[SB] Issue 3120 fixed , Unable to create 'Tower of Hanoi' active task with Custom schedule

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyActiveTasksDAOImpl.java

issue #3119  fixed-Unable to delete active tasks

[SB] issue #3119 -Unable to delete active tasks

---

deployment/mystudies.hcl
deployment/terraform/kubernetes/main.tf

Pin k8s provider version

---

participant-manager/src/environments/environment.prod.ts

PM web app Formatting issue fixed -issue #3154 fixing

PM web app Formatting issue fixed

---

study-datastore/src/main/java/com/hphc/mystudies/util/StudyMetaDataUtil.java

Issue  #3158 , #3159 - Studies which are configured for only Android in SB are not displaying in android mobile application

[Study Datastore]Issue  #3158 , #3159 - Studies which are configured for only Android in SB are not displaying in android mobile application

---

study-builder/fdahpStudyDesigner/src/main/webapp/js/common.js

Allow Right Click across application . Issue #3152 fix

[v2.0.3][Study Builder]Allow Right Click across application

---

common-modules/common-service/pom.xml
common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/CleanPropertyAdvice.java

This PR contains the back end changes for handling XSS issue #2648 fix .

[v2.0.3] [Participant Manager Datastore] XSS issue fix

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp

Fixed issue #3037: Used `visibility:hidden` attribute to hide the delete icon when there is only one run
#2965: Added conditional check to remove the delete icon from conditional based formula function

[v2.0.3] [SB]: Fixed issue #3037 #2965

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp

Issue #3225: Added Time picker to be displayed for all runs

[v2.0.3] fixed issue #3225

---

common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/AuditEventServiceImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/AuditEventServiceImpl.java
study-datastore/src/main/java/com/hphc/mystudies/service/AuditEventService.java

Stack Driver logging client not shut down properly issue #2058   fix

Stack Driver logging client not shut down properly issue fix

---

study-datastore/src/main/java/com/hphc/mystudies/web/servlet/AuthenticationService.java

Validate AppToken and BundleId belongs to same Platform. Fix for the issue #1714

[Study Datastore] validate apptoken and bundleid belongs to same platform type

---

participant-manager/src/app/_helper/validator.ts
participant-manager/src/app/auth/set-up-account/set-up-account.component.html
participant-manager/src/app/auth/set-up-account/set-up-account.component.scss
participant-manager/src/app/auth/set-up-account/set-up-account.component.ts
participant-manager/src/app/shared/error.codes.enum.ts
participant-manager/src/app/site-coordinator/account/change-password/change-password.component.html
participant-manager/src/app/site-coordinator/account/change-password/change-password.component.scss
participant-manager/src/app/site-coordinator/account/change-password/change-password.component.ts
participant-manager/src/styles.scss

Fixed issue #2646, Password strength meter for 'New Password' fields for the below pages:
1. Change password page
2. Set up account page (for new user)
3. Set up password page (post forgot password/ account lock flow)

[v2.0.3] Fixed issue #2646, Password Strength Meter

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp

[SB] Unable to schedule the the Questionnaries in the study #3264
Removed extra else condition.

[v2.0.3] Fixed issue #3264 [SB] Unable to schedule the the Questionnaries in the study 

---

Android/app/src/main/java/com/harvard/studyappmodule/consent/ConsentBuilder.java

fixes for #3301 by changing the ID value

[v2.0.3] Android - fixes for #3301

---

documentation/API/README.md

README.md for API documentation

README.md for API documentation

---

documentation/whats-new.md

Wait to commit until API documentation readme is added.

Add 2.0.3 to What's New

---

.github/workflows/build-auth-server.yml
.github/workflows/build-participant-consent-datastore.yml
.github/workflows/build-participant-enroll-datastore.yml
.github/workflows/build-participant-manager-datastore.yml
.github/workflows/build-participant-user-datastore.yml
.github/workflows/build-response-datastore.yml
.github/workflows/build-studybuilder.yml
auth-server/oauth-scim-service/pom.xml
common-modules/common-service/pom.xml
common-modules/common-tests/pom.xml
participant-datastore/consent-mgmt-module/consent-mgmt/pom.xml
participant-datastore/enroll-mgmt-module/enroll-mgmt/pom.xml
participant-datastore/user-mgmt-module/user-mgmt/pom.xml
participant-manager-datastore/participant-manager-service/pom.xml
response-datastore/response-server-service/pom.xml
study-builder/Dockerfile
study-builder/cloudbuild.yaml
study-builder/fdahpStudyDesigner/pom.xml
study-datastore/Dockerfile
study-datastore/cloudbuild.yaml
study-datastore/pom.xml

Maven Compiler/Lombok Error When Building App Container Images issue #3409  fix

Issue #3409 build failure for all services fix [master]

---

participant-datastore/consent-mgmt-module/consent-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/UserConsentManagementController.java

This PR contains the issue fixes for issue #3418 .
Folder structure is now updated in the Cloud storage.
New folder structure is like Study > Participant-specific ID (different from Participant ID) > Consent Pdfs

[v2.0.4] Issue 3418 fixes

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentInfo.jsp

This PR contains the issue fixes for issue #3398 .
- `Done button` is now validating for add and edit consent section for Firefox browser.

[v2.0.4] Issue 3398 fixes

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentInfo.jsp

This PR contains the issue fixes for issue #3380 .
- `save button `is now working as expected and saving data as draft.

[v2.0.4] Issue 3380 fixes

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentInfoList.jsp

This PR contains the issue fixes for issue #3378 .
-  `Consent Title` is corrected to `Section Title`.

[v2.0.4] Issue 3378 fixes

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/userPasswordReset.jsp

This PR contains the issue fixes for issue #3358 .
For this issue fixes: 
- User is now able to navigate back to the sign in screen when user click on the logo of the application.

[v2.0.4] Issue 3358 fixes

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyServiceImpl.java

This PR contains the issue fixes for issue #3306  .
Rich text format is corrected for `/adminStudies/saveOrUpdateResource.do` end point.

[v2.0.4] Issue 3306 fixes

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewFetalStudyActiveTask.jsp

This PR contains the issue fixes for issue #3277 .
`Activity short title or key` error message is now displaying after correction.

[v2.0.4] Issue 3277 fixes

---

participant-manager/src/app/site-coordinator/apps/app-details/app-details.component.html
participant-manager/src/app/site-coordinator/apps/app-list/app-list.component.html
participant-manager/src/app/site-coordinator/location/location-list/location-list.component.html
participant-manager/src/app/site-coordinator/participant-details/participant-details.component.html
participant-manager/src/app/site-coordinator/sites/site-details/site-details.component.html
participant-manager/src/app/site-coordinator/sites/site-list/site-list.component.html
participant-manager/src/app/site-coordinator/studies/study-details/study-details.component.html
participant-manager/src/app/site-coordinator/studies/study-list/study-list.component.html
participant-manager/src/app/site-coordinator/user/user-details/user-details.component.html
participant-manager/src/app/site-coordinator/user/user-list/user-list.component.html

…the placeholder.
fixed UI issue #3435 For all PM screens that have tables and display the placeholder.

[v2.0.5] PM Web app issue #3435 fixing

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/templates/studyMenu.jsp

Fixed issue #3448, by removing extra braces in `studyMenu.jsp`

[v2.0.5] Fixed issue #3448

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentReviewAndEConsentPage.jsp

#3456 [SB][QA] E-Consent Steps screen > Save/Cancel/Mark as Completed buttons are non functional

[v2.0.5] Fixed issue #3456  [SB][QA] E-Consent Steps screen > Save/Cancel/Mark as Completed buttons are non functional 

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp

Issue #3442 fixes - Add/Edit questionnaires > Fields are not displayed in 'Response level attributes' tab for the following response types

[v2.0.5] Fixed Issue #3442

---

Android/app/src/main/java/com/harvard/studyappmodule/custom/activetask/Tappingactivity.java

[V2.0.5] Android - #3423

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/LoginServiceImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/UsersServiceImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/EmailNotification.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/Mail.java
study-builder/fdahpStudyDesigner/src/test/java/com/fdahpstudydesigner/common/BaseMockIT.java
study-builder/fdahpStudyDesigner/src/test/java/com/fdahpstudydesigner/config/WebAppTestConfig.java

Issue #3467  fixed - Email mocking failed for static methods

[v2.0.5] Issue 3467 fixes

---

participant-datastore/user-mgmt-module/user-mgmt/src/main/resources/application.properties
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/Mail.java
study-builder/fdahpStudyDesigner/src/main/resources/application.properties

#3453 issue fixed - Need to Support multiple Email Providers.

[v2.0.5] Fixed Issue #3453

---

participant-manager/src/app/site-coordinator/participant-details/participant-details.component.html

[v2.0.5] Pm web issue #3443 fixing

---

participant-manager/src/assets/css/root.scss

fixed responsive issue 3477 multiple logo displaying.

[v2.0.5] Pm web app issue 3477 fixing

---

common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/repository/AuthInfoRepository.java
participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/dao/UserProfileManagementDaoImpl.java
participant-datastore/user-mgmt-module/user-mgmt/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/UserProfileControllerTest.java
participant-datastore/user-mgmt-module/user-mgmt/src/test/java/com/google/cloud/healthcare/fdamystudies/testutils/Constants.java

This PR contains the issue fixes for issues #1825 and #2868 .
`/updateUserProfile` endpoint implementation is modified in participant-datastore.

[v2.0.5] Issue 1825 and 2868 fixes

---

study-datastore/pom.xml
study-datastore/src/main/java/com/hphc/mystudies/dao/ActivityMetaDataDao.java
study-datastore/src/main/java/com/hphc/mystudies/dao/AppMetaDataDao.java
study-datastore/src/main/java/com/hphc/mystudies/dao/DashboardMetaDataDao.java
study-datastore/src/main/java/com/hphc/mystudies/dao/StudyMetaDataDao.java
study-datastore/src/main/java/com/hphc/mystudies/integration/ActivityMetaDataOrchestration.java
study-datastore/src/main/java/com/hphc/mystudies/integration/AppMetaDataOrchestration.java
study-datastore/src/main/java/com/hphc/mystudies/integration/DashboardMetaDataOrchestration.java
study-datastore/src/main/java/com/hphc/mystudies/integration/StudyMetaDataOrchestration.java
study-datastore/src/main/java/com/hphc/mystudies/service/AuditEventService.java
study-datastore/src/main/java/com/hphc/mystudies/service/StudyMetaDataService.java
study-datastore/src/main/java/com/hphc/mystudies/util/HibernateUtil.java
study-datastore/src/main/java/com/hphc/mystudies/util/PropertiesUtil.java
study-datastore/src/main/java/com/hphc/mystudies/util/StudyMetaDataUtil.java
study-datastore/src/main/java/com/hphc/mystudies/web/servlet/AuthenticationService.java
study-datastore/src/main/java/com/hphc/mystudies/web/servlet/RestAuthenticationFilter.java
study-datastore/src/main/java/com/hphc/mystudies/web/servlet/StudyMetaDataController.java

Fixed issue #499 by replacing logger statements with Xlogger entry and exit methods

[v2.0.5] - Fixed Issue #499 in Study datastore

---

study-builder/fdahpStudyDesigner/pom.xml
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/common/PlaceholderReplacer.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/DashBoardAndProfileController.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/LoginController.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/NotificationController.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyActiveTasksController.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyQuestionnaireController.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/UsersController.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/scheduler/FDASchedulerService.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/ApplicationInitializer.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/CrossScriptingFilter.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/EmailNotification.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerPreHandlerInterceptor.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerUtil.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/LimitLoginAuthenticationProvider.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/Mail.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/PropertiesUtil.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/RequestWrapper.java
study-builder/fdahpStudyDesigner/src/test/java/com/fdahpstudydesigner/common/BaseMockIT.java

Fixed issue #499 by replacing logger statements with Xlogger entry and exit methods

[v2.0.5] - Fixed issue #499 in Study Builder

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/AuditLogDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/DashBoardAndProfileDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/LoginDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/NotificationDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyActiveTasksDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyQuestionnaireDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/UsersDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/AuditEventServiceImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/DashBoardAndProfileServiceImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/LoginServiceImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/NotificationServiceImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyActiveTasksServiceImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyQuestionnaireServiceImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyServiceImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/UsersServiceImpl.java

[v-2.0.5] - Fixed issue #499

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp

Fixed issue #3530 : added required attribute.

[v2.0.5] Fixed issue  #3530

---

iOS/MyStudies/MyStudies/Controllers/StudyUI/ResourceUI/ResourcesViewController.swift
iOS/MyStudies/MyStudies/Controllers/StudyUI/StudyOverviewUI/StudyHomeViewController.swift
iOS/MyStudies/MyStudies/Networking/APIs/UserServices.swift
iOS/MyStudies/MyStudies/Utils/Extension/String+Extensions.swift

Bug Fixes for
#3424 , #3537 , #3319

[v2.0.5] iOS-Fixed issue #3424, #3537, #3319

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/bean/StudyListBean.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/UsersDAOImpl.java

Issue #3549 fixed - Studies tab > Deactivated studies are not getting displayed in the studies list for the newly created super admins in the following scenario

[v2.0.5] Fixed issue #3549 

---

db-migration/study-builder-db-migration/db/migration/V2_0_5__release.sql
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/bo/NotificationBO.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerUtil.java

Issue #3508 fixed - [QA] Push notifications not triggered from SB.

[v2.0.5] Fixed issue #3508

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditStudyNotification.jsp

Fixed issue #3555, in Study level Notification.

[v2.0.5] Fixed issue #3555

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/bo/ActiveTaskBo.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyActiveTasksController.java
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewFetalStudyActiveTask.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewSpatialStudyActiveTask.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewTowerStudyActiveTask.jsp

Fixed #3563 issue- [SB] Active task > Success message needs to be corrected when a user adds an active task

[v2.0.5] Fixed issue #3563

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewSettingAndAdmins.jsp

Fixed #3572 issue- [SB] Study settings page > Wrong error message is getting displayed for the study settings page.

[v2.0.5] Fixed issue #3572

---

auth-server/oauth-scim-service/src/main/resources/static/css/style.css
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentReviewAndEConsentPage.jsp

- [SB] Create/Edit study > E-consent steps > Data sharing permission > Text case usage issue #3586
- [Auth server][Mobile apps] Sign in screen > UI issue #3506

[v2.0.6] Fixed UI issues  [SB] #3586 and [Auth server] #3506

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/templates/studyMenu.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp

[v2.0.6] Fixed Issue #3582 #3559

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/addOrEditUserPage.jsp

Fixed issue #3581, in the studies dropdown

[v2.0.6] Fixed issue #3581

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditResourcePage.jsp

This PR contains the issue fixes for issue #3558 .

[v2.0.6] Issue #3558 Fixes

---

participant-manager/src/app/auth/set-up-account/set-up-account.component.html
participant-manager/src/app/auth/set-up-account/set-up-account.component.scss
participant-manager/src/app/auth/set-up-account/set-up-account.component.ts
participant-manager/src/app/site-coordinator/account/change-password/change-password.component.html
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/overViewPage.jsp

Fixed issues:
#3621  - [SB] Overview screen > Images are getting removed for the following scenario 
#3615  - [PM] Setup account screen > Password criteria icon is not getting displayed
#3596  -  [PM] Need to increase detectable area for Password Criteria icon (?) in change Password screen

[v2.0.6] Issue #3621 #3615 #3596 

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyQuestionnaireServiceImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyServiceImpl.java
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentInfo.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentReviewAndEConsentPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/overViewPage.jsp
study-datastore/pom.xml
study-datastore/src/main/java/com/hphc/mystudies/dao/StudyMetaDataDao.java

Fixed Issue #1288: fixed summernote editor
#3526 : fixed auto-created consent document
#3540,#3579 : Summernote formatting fixed
#3601 : HTML is breaking in Review and E-Consent page

[v2.0.6] Issue #1288 #3526 #3540 #3579 #3601 fixes

---

study-datastore/pom.xml

Fixed issue [Mobile] Studies are not displaying in Study list screen in mobile #3609
Issue: was throwing 500 error org.glassfish.jersey.server.ContainerException: java.lang.NoSuchMethodError: &#39;boolean com.fasterxml.jackson.databind.JavaType.isReferenceType()&#39;
Fix: changed jackson dependency which contains isReferenceType() method

[v2.0.6] Fixed issue [Mobile] Studies are not displaying in Study list screen in mobile #3609

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/templates/studyMenu.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp

[v2.0.6] Fixed Issue #3608 #3612

---

db-migration/study-builder-db-migration/db/migration/V2_0_6__release.sql

This PR contains the issue fixes for issue #3551 .

[v2.0.6] Issue 3551 Fixes

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/instructionsStep.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp

Fixed issues:
- #3627  - [SB] Overview screen > Images are getting removed for the following scenario.
- #3633  - [SB] Instruction step is not saving on pasting a copied paragraph contents from other sources.

[v2.0.6] Issue #3627, #3633

---

auth-server/oauth-scim-service/src/main/java/com/google/cloud/healthcare/fdamystudies/oauthscim/controller/LoginController.java
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionList.jsp

Fixed issues:
1. [Hydra] Sign in > Entered password is removing Bug Hydra P2 Process: Fixed Process: Tested dev #3204
Issue: Mobile app was redirecting the new user to login page once.
Fix: Temporary registry ID is used only once while creating new user, which will be used for auto login. 
So, deleting the TEMP_REG_ID from COOKIE. Once TEMP_REG_ID is deleted from COOKIE, app will continue with normal authentication and login flow.
2. [SB] Comprehension test > 'Mark as completed' button is non functional #3643

[v2.0.6] Fixed issues oauth server 3204, study builder 3643

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp

#3677  issue fixed - [SB] unable to create following active task with anchor date based schedule with weekly frequency

[v2.0.6] Issue #3677 fixes

---

participant-manager/src/app/site-coordinator/account/account-profile/account-profile.component.html
participant-manager/src/app/site-coordinator/account/change-password/change-password.component.html
participant-manager/src/app/site-coordinator/mobile-menu/mobile-menu.component.html
participant-manager/src/assets/css/theme-layout.scss

[v2.0.6]-issues fixed-#3489, #3488, #3487, #3484, #3483, #3477, #3474, #3472, #3471

---

common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/common/ErrorCode.java
common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/repository/LocationRepository.java
common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/repository/SiteRepository.java
participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/LocationServiceImpl.java
participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/task/ChangeDefaultLocation.java
participant-manager/src/app/shared/error.codes.enum.ts

- Fixed issue #3607, by not displaying the default location in the location list and by adding @PostConstruct method to change the default location with new default location ID to `default_OpnStdy` and default location name to `defaultLocation_OpenStudy` 
- Fixed issue #3626, by adding Error Messages when location ID and location name is the same as the default location ID and default location name.

[v2.0.6] - Fixed issue #3607 and #3626

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/notification/createOrUpdateNotification.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditResourcePage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditStudyNotification.jsp

Issue fixes:
#3651 : [SB] > Notifications > Text change for Add/Edit/ Resend/ Copy notifications screen Bug
#3652 : [SB] Notifications > Selected date for scheduling is getting removed
#3690 : [SB] Resources > Custom schedule > Start date is getting removed

[v2.0.6] Issue #3651 #3652 #3690 fixed

---

auth-server/oauth-scim-service/pom.xml
common-modules/common-tests/pom.xml
participant-datastore/consent-mgmt-module/consent-mgmt/pom.xml
participant-manager-datastore/participant-manager-service/pom.xml
participant-manager/package-lock.json
study-builder/fdahpStudyDesigner/pom.xml
study-datastore/pom.xml

This PR contains the issue fixes for dependency issue #3665 .
Angular dependency corrections will be addressed in a separate PR.

[v2.0.6] Dependency issue fixes

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/notification/createOrUpdateNotification.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditStudyNotification.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/css/style.css

Fixed issues :
[SB] Notifications > Change the error message text when entered time has expired #3685
[SB] Text in the pop-up should be center-aligned #3653

[v2.0.6] Study builder, Issues fixed 3685 3653

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditResourcePage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyNotificationList.jsp

- Fixed issue #3718 - Text updated to `Scheduling options`
- Fixed issue #3684 - Study Notifications list >Status should be changed to `Draft` for notifications which are in draft state
- Fixed issue #3709 - Resources are getting displayed in mobile app irrespective of scheduled date

[v2.0.6] - Fixed issue #3718,#3684,#3709

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp

Fixed issue #3686 [SB] Active task > Add to chart > Values in the 'Time range for the chart' dropdown getting duplicated
Fix: Added validation before appending data in dropdown to avoid duplication.

[v2.0.6] Fixed issue #3686 [SB] Active task > Add to chart > Values in the 'Time range for the chart' dropdown getting duplicated 

---

study-datastore/src/main/java/com/hphc/mystudies/dao/StudyMetaDataDao.java

This PR contains the issue fixes for issue #3628 .

[v2.0.6] Issue 3628 fixes

---

iOS/MyStudies/MyStudies/Models/Consent/ConsentBuilder/ConsentBuilder.swift

[v2.0.6] iOS-Fixed issue # 3580

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyActiveTasksDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerUtil.java
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditResourcePage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp

Issues fixed:
#3719 : [SB] Resources > Study builder should not accept the PDF file with size more than 5MB
#3737 : [SB] Active tasks > Unable to add an active task with custom start date and study lifetime 
#3700 : [SB] Active task > Schedule tab > One time / Custom schedule > Start and/or end date is not getting displayed

[v2.0.6] Issue #3719 #3737 #3700 fixed

---

Android/app/build.gradle
Android/app/src/main/java/com/harvard/studyappmodule/StudyInfoPagerAdapter.java
Android/app/src/main/java/com/harvard/studyappmodule/StudyListAdapter.java

changed glide implementation to load images #3509

[v2.0.6] - Android - fixes for #3509

---

study-datastore/src/main/java/com/hphc/mystudies/dao/ActivityMetaDataDao.java

This PR contains the issue fixes for issue #3739 .

[v2.0.6] - Issue 3739 fixes

---

Android/app/src/main/java/com/harvard/studyappmodule/SurveyActivitiesFragment.java
Android/app/src/main/java/com/harvard/studyappmodule/activitylistmodel/AnchorRuns.java
Android/app/src/main/java/com/harvard/utils/AppController.java
Android/app/src/main/java/com/harvard/utils/realm/RealmMigrationHelper.java

fix for #2447 separated time to start and end time

[v2.0.6] - Android- fixes for #2447

---

iOS/MyStudies/MyStudies/Models/Consent/ConsentBuilder/ConsentBuilder.swift
iOS/MyStudies/MyStudies/Views/Steps/ConsentStep/ConsentStep.swift

[v2.0.6] iOS-Fixed issue # 3731 

---

iOS/MyStudies/MyStudies/Controllers/StudyUI/ActivityUI/ActivitiesViewController.swift
iOS/MyStudies/MyStudies/Controllers/StudyUI/ChartsUI/ChartsViewController.swift
iOS/MyStudies/MyStudies/Controllers/StudyUI/StudyDashboardUI/StudyDashboardViewController.swift

[v2.0.6] iOS-Fixed issue # 3404 

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewFetalStudyActiveTask.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewSpatialStudyActiveTask.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewTowerStudyActiveTask.jsp

Fixed issue #3751 : Fixed overlap error message.

[v2.0.6] Fixed issue #3751

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
study-datastore/src/main/java/com/hphc/mystudies/dao/ActivityMetaDataDao.java

Issues fixed:
#3750 : [SB] One Time > Previously entered data is getting retained for 'startTime' and 'endTime' in the GetStudyActivityList API in one of the scenario

[v2.0.6] Issue #3750 fixed

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp

Fixed issue #3743, Questionnaires/Active task > Custom schedule > Use proper text case for the error messages

[v2.0.6] Fixed issue #3743

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentReviewAndEConsentPage.jsp

#3792 : [SB] Consent sections created are not reflecting in Auto-created consent document

[v2.0.6] Fixed Issue #3792

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/CustomSuccessHandler.java
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/templates/copyright.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionList.jsp

Fixed issues
- #3787 #3788 : changed property name
- #3791 : modified Jsp file 
- #3789 : added version information in footer

[v2.0.6] Fixed Issue #3787 #3788 #3791

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyExportImportService.java
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/templates/subheader.jsp

Fixed issue 
#3788 : removed condition
#3793 : set `ExportSignedUrl ` to `null`

[v2.0.6] Fixed issue #3788 #3793

---

iOS/MyStudies/MyStudies/Controllers/StudyUI/StudyDashboardUI/StudyDashboardViewController.swift
iOS/MyStudies/MyStudies/Models/Database/DBHandler.swift
iOS/MyStudies/MyStudies/Networking/APIs/ResponseServices.swift

[v2.0.6] iOS-Fixed issue # 3716

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentReviewAndEConsentPage.jsp

Fixed issue #3796, E-Consent steps > Consent document tab > Highlighted text should be removed.

[v2.0.6] Fixed issue #3796

---

study-datastore/src/main/java/com/hphc/mystudies/dao/DashboardMetaDataDao.java

Fixed issue #3682, [Mobile apps] Dashboard stats are not displaying for some studies

[v2.0.6] Fixed issue #3682

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
study-datastore/src/main/java/com/hphc/mystudies/dto/StudyPageDto.java

Fixed issue #3807, [SB] [Import] Overview > Order of the overview pages is getting changed in mobile apps.

[v2.0.6] Fixed issue #3807

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/DashBoardAndProfileController.java
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/myAccount.jsp

Fixed issue #3817, Account Manager text should be removed in my account screen

[v2.0.6] Fixed issue #3817

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/templates/subheader.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/actionListPage.jsp

Fixed issue #3812: Added URL encoding to avoid downloading signed URL directly from the browser.
#3813 : modified Jsp file

[v2.0.6] Fixed Issue #3812  #3813

---

iOS/MyStudies/MyStudies/Controllers/GatewayUI/ProfileViewUI/ProfileViewController.swift
iOS/MyStudies/MyStudies/Controllers/GatewayUI/SlideMenu/LeftMenuViewController.swift
iOS/MyStudies/MyStudies/Controllers/LoginRegisterUI/GatewayOverviewUI/HomeViewController.swift

[v2.0.6] iOS-Fixed issue #3186

---

iOS/MyStudies/MyStudies/Models/Consent/ConsentBuilder/ConsentBuilder.swift

[v2.0.6] iOS-Fixed issue #3815

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java

Fixed issue #3829 [SB] Clicking on 'Actions' study zone section navigating to studies list and hence unable to perform any actions
Added null check for getExportSignedUrl()

[v2.0.6] Fixed issue #3829 [SB] Clicking on 'Actions' study zone section navigating to studies list and hence unable to perform any actions

---

Android/app/build.gradle

[V2.0.6] Android - #3495

---

Android/app/src/main/java/com/harvard/studyappmodule/StudyListAdapter.java

[V2.0.6] Android - #3509 

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyExportImportService.java

#3802 : [SB] [Copy/Import] Edit eligibility question > 'Question key or short title' field is disabled Bug

[v2.0.6] Fixed issue #3802 

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java

Fixed issue #3833: Added fix to make created studies to be displayed on studies list screen based on the imported time.

[2.0.6] Fixed issue #3833

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/NotificationDAOImpl.java

Fixed issue #3835, App level notifications > Order of the notifications should be displayed based on the created date and time.

[v2.0.6] Fixed issue #3835

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionQuestion.jsp

Fixed issue-#3845, [SB] Comprehension test > Add comprehension test > One of the answer options is getting removed for the scenario

[v2.0.6] Fixed issue-#3845

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp

[SB] Questionnaires/Active task > Anchor based > Schedule tab > Validations needs to be handled for custom schedule #3769
[SB] Active tasks > Schedule tab > Anchor date based > Custom schedule > UI issue #3459

[v2.0.6] Fixed study builder issues 3769 and 3459 Validations needs to be handled for custom schedule 

---

participant-manager/src/app/error/error.component.scss
participant-manager/src/app/page-not-found/page-not-found.component.scss
participant-manager/src/assets/css/theme-layout.scss
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewFetalStudyActiveTask.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewSpatialStudyActiveTask.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewTowerStudyActiveTask.jsp

Fixed Issue -
#3717 [SB] Add active task > Contents tab Add to line chart > Radio button issue for 'Allow rollback of chart'.
#3816 and #3711 in Participant Manager.

[v2.0.6] Fixed Issue #3717, #3816 and #3711

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/instructionsStep.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/overViewPage.jsp

Fixed issue
#3722 : page collapsed issue fix
#3841 : added validation
#3858 : added validation

[v2.0.6] Fixed Issue #3722, #3841 and #3858

---

participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/service/StudiesServicesImpl.java
participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/util/AppConstants.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/bean/PushNotificationBean.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/scheduler/FDASchedulerService.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerConstants.java

This PR contains the issue fixes for issue #3714 .

[v2.0.6] Issue 3714 fixes

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/notification/createOrUpdateNotification.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditStudyNotification.jsp
study-datastore/src/main/java/com/hphc/mystudies/dao/ActivityMetaDataDao.java

Fixed issues 
[SB] Anchor date based custom scheduling > Order of anchor runs is incorrect in GetStudyActivityList API #3848
Fix: Used case to sort anchor date time, -ve in desc and +ve in asc order.
[SB] Active tasks > Daily > Anchor days value is incorrect in GetStudyActivityList API #3739
[SB] Add info icon text for notification scheduling #3160 UI issue

[v2.0.6] Fixed issues #3848, #3160 and #3739 study builder/datastore GetStudyActivityList API

---

Android/app/src/main/java/com/harvard/usermodule/LoginCallbackActivity.java
Android/app/src/main/java/com/harvard/utils/AppController.java

fixed issue reading value from deeplink value - #3881

[V2.0.6] Android - #3881

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
study-datastore/src/main/java/com/hphc/mystudies/dao/ActivityMetaDataDao.java

Fixed issue 
#3800 : added `createdBy` to `studyBo`
#3871 : added a condition to check the values

[v2.0.6] Fixed issue #3800 #3871

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentInfo.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/instructionsStep.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp

Fixed issue
#3846 [SB] Issue when user clicks on Save button
#3622 [SB] Questionnaires/Active tasks > Schedule tab > Data display issue when switching schedule type

[v2.0.6] Fixed Issue #3846 #3622

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerUtil.java

Issue Fixed:
#3854 : [SB] [Import] Resources > Some of the resource PDF's file fails to import for imported study

[v2.0.6] Fixed issue #3854

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp

#3772 fixed : [SB] Questionnaires > Anchor based > Unable to enter time from 2nd run onwards for daily frequency

[v2.0.6] Fixed issue #3772

---

deployment/README.md

changing the prefix and env for service account.

Read me file change

---

db-migration/study-builder-db-migration/db/migration/V2_0_6__release.sql

Updated study builder DB migration script V2_0_6__release.sql

[v2.0.6] Updated study builder DB migration script V2_0_6__release.sql

---

db-migration/study-builder-db-migration/db/migration/V2_0_6__release.sql
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/bo/StudyBo.java
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/ApplicationContext.xml

[v2.0.6] Db migration issue fixed 

---

Android/app/src/main/java/com/harvard/utils/realm/RealmMigrationHelper.java

[v2.0.6] Android - issue fix for #3022 - migration

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyExportImportService.java

[v2.0.6] Fixed issue #3902

---

iOS/MyStudies/MyStudies/Controllers/GatewayUI/SlideMenu/LeftMenuViewController.swift
iOS/MyStudies/MyStudies/Controllers/LoginRegisterUI/RegisterUI/SignUpViewController.swift
iOS/MyStudies/MyStudies/Controllers/StudyUI/ActivityUI/ActivitiesViewController.swift
iOS/MyStudies/MyStudies/Info.plist
iOS/MyStudies/MyStudies/Storyboards/FetalKickCounter.storyboard
iOS/MyStudies/MyStudies/Storyboards/Login.storyboard
iOS/MyStudies/MyStudies/Storyboards/Study.storyboard
iOS/MyStudies/MyStudies/Utils/Helpers/Constants/Constants.swift
iOS/MyStudies/MyStudies/Utils/Resources/Localizable/LocalizableString.swift
iOS/MyStudies/MyStudies/Utils/Resources/Plists/UI/SignUpPlist.plist

[v2.0.7] iOS Fixes for - #3082

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/overViewPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp

Fixed issue
#3861 : [SB] Questionnaires > Previously selected and saved radio button should be displayed
#3880 : [SB] Overview screen > Description field > Data entered in different font styles is getting converted to 'Roboto' style
#3893 : [SB] Questionnaires/Active task > Regular > Monthly frequency > Getting error message when admin clicks on done button

[v2.0.7] Fixed issue #3861 #3880 #3893

---

participant-manager/src/app/site-coordinator/mobile-menu/mobile-menu.component.html
participant-manager/src/app/site-coordinator/mobile-menu/mobile-menu.component.ts
participant-manager/src/app/site-coordinator/sitecoordinator.component.html
participant-manager/src/app/site-coordinator/sitecoordinator.component.ts
participant-manager/src/assets/css/root.scss
participant-manager/src/assets/css/theme-layout.scss

#3473 fixed - [PM] Search bar > Responsive issue

[v2.0.7] - Fixed Issue - #3473

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp

Fixed issue 
#3879, [SB] Questionnaires/Active > Regular > Custom schedule > End date field > Calendar issue

[v2.0.7] Fixed issue #3879

---

iOS/MyStudies/MyStudies/Controllers/EligibilityUI/EligibilityStepViewController.swift

[v2.0.7] iOS Fixes for - #1972 Enrollment screen UI issue

---

study-datastore/src/main/java/com/hphc/mystudies/dto/ComprehensionTestResponseDto.java

fixed issue #3919: Added order by to sort the comprehension test responses based on `sequenceNumber`

[v2.0.7] Fixed issue #3919

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp

Fixed issue #3894, [SB] Active task > Schedule tab > Regular > Error message should be displayed

[v2.0.7]Fixed issue #3894

---

participant-manager/src/app/site-coordinator/studies/update-target/update-target.component.html
participant-manager/src/app/site-coordinator/studies/update-target/update-target.component.ts

Fixed issue
#3896 : [PM] Open study > Enrollment registry > Enrollment target > Text case issue

[v2.0.7] Fixed issue #3896

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyQuestionnaireDAOImpl.java

Fixed issue #3930: [SB] Questionnaires > fixed functional issue for the copied questionnaires

[v2.0.7] Fixed issue #3930

---

participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/UserProfileController.java
participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/service/UserRegistrationServiceImpl.java
participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/util/AppConstants.java
participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/util/MyStudiesUserRegUtil.java

Fixed issue #3904, by excluding I: capital i, l: small L, 0: zero, O: capital o and o: small o when generating verification code.

[v2.0.7] Fixed issue #3904

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp

This PR contains the issue fixes for issue #3895.

[v2.0.7] Issue 3895 fixes

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/addOrEditUserPage.jsp

Fixed issue 
#3951, [SB] Delete icon is not working in the assigned permissions section in admin details page
#3959, [SB] Text correction is required

[v2.0.7] Fixed issue #3951 and #3959

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/templates/layout.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp

#3935 issue fixed : [SB] Questionnaires/Active task > Schedule tab > Time picker is not working for the following scenario

[v2.0.7] Fixed issue #3935

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/overViewPage.jsp

This PR contains the issue fixes for issue #3972 .

[V2.0.7] Issue 3972 fixes

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp

Fixed issue 3976 [SB] Active task > Schedule tab > Custom schedule > UI issues

[v2.0.7] Fixed issue #3976 [SB] Active task > Schedule tab > Custom schedule > UI issues

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyServiceImpl.java

Fixed issue 
[SB] Resources > If text for notifying participant about a resource is not entered, blank notification is triggered in mobile apps #3900

[v2.0.7] Fixed issue #3900 study builder notification 

---

participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/SiteServiceImpl.java
participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/StudyServiceImpl.java
participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/util/ParticipantManagerUtil.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyQuestionnaireDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyServiceImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerUtil.java
study-datastore/pom.xml
study-datastore/src/main/java/com/hphc/mystudies/dao/ActivityMetaDataDao.java
study-datastore/src/main/java/com/hphc/mystudies/dao/StudyMetaDataDao.java
study-datastore/src/main/java/com/hphc/mystudies/service/StudyMetaDataService.java
study-datastore/src/main/java/com/hphc/mystudies/util/StudyMetaDataConstants.java
study-datastore/src/main/java/com/hphc/mystudies/util/StudyMetaDataUtil.java

#3938 issue fixed: Access of resources for client applications without GCP cloud storage signed URLs

[v2.0.7] Fixed issue #3938 for Study builder, Study datastore and Participant manager datastore

---

Android/app/src/main/java/com/harvard/storagemodule/DbServiceSubscriber.java
Android/app/src/main/java/com/harvard/studyappmodule/ResourcesListAdapter.java
Android/app/src/main/java/com/harvard/studyappmodule/ResourcesWebViewActivity.java
Android/app/src/main/java/com/harvard/studyappmodule/StudyInfoPagerAdapter.java
Android/app/src/main/java/com/harvard/studyappmodule/StudyListAdapter.java
Android/app/src/main/java/com/harvard/studyappmodule/custom/question/ContinuousScaleQuestion.java
Android/app/src/main/java/com/harvard/studyappmodule/custom/question/MultiChoiceImageQuestionBody.java
Android/app/src/main/java/com/harvard/studyappmodule/custom/question/ScaleQuestion.java

[v2.0.7] Android - issue fix for #3938

---

iOS/MyStudies/MyStudies/Controllers/StudyUI/ResourceUI/ResourceDetailViewController.swift
iOS/MyStudies/MyStudies/Views/Steps/ActivityStep/ActivityQuestionStep.swift

[v2.0.7] iOS Fixes for #3938

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/loginPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/myAccount.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/signUpPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/basicInformation.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/addOrEditUserPage.jsp

#3982 issue fixed: [SB] Email field is not allowing the Domain name extension with more than 3 characters

[v2.0.7] Fixed issue #3982 

---

Android/app/src/main/java/com/harvard/studyappmodule/ChartActivity.java
Android/app/src/main/java/com/harvard/studyappmodule/ConsentCompletedActivity.java
Android/app/src/main/java/com/harvard/studyappmodule/PdfDisplayActivity.java
Android/app/src/main/java/com/harvard/studyappmodule/SurveyDashboardFragment.java

[v2.0.7] Android - issue fix for #3998

---

Android/app/src/main/java/com/harvard/usermodule/TermsPrivacyPolicyActivity.java

Fix for terms and privacy link broken for sign in page

[v2.0.7] Android - issue fix for terms and privacy link broken 

---

study-builder/fdahpStudyDesigner/src/main/resources/application.properties

Fixed issue #4008: Modified release version in `application.properties` file

[v2.0.7] Fixed issue #4008

---

study-datastore/src/main/java/com/hphc/mystudies/dao/ActivityMetaDataDao.java
study-datastore/src/main/java/com/hphc/mystudies/dto/ActiveTaskDto.java

Fixed issue #3980 : Active tasks are getting duplicated for the study in a scenario

[v2.0.8] Fixed issue #3980

---

participant-manager/src/app/site-coordinator/user/new-user/new-user.component.html
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/resourceListPage.jsp

Issues fixed:
#3987 :  [SB] Resources > Blue tick mark is not getting removed on the side menu bar for the following scenario
#3923 : [PM] Admins > Add new admin screen > UI issue

[v2.0.8] Fixed issue #3987 and #3923 

---

iOS/MyStudies/MyStudies/Controllers/LoginRegisterUI/RegisterUI/SignUpViewController.swift
iOS/MyStudies/ResearchKit/Common/ORKAnswerFormat.m

[v2.0.8] iOS Fixes for - #3955, #3981

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyActiveTasksDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAO.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyExportImportService.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyServiceImpl.java

[v2.0.8] Fixed issue #3986 #4013

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAO.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyQuestionnaireDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyExportImportService.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyServiceImpl.java

Fixed issue 
#4024 : [SB] [Copy/Import last published version] Questionnaires are getting duplicated for imported study in a scenario
#4026 : [SB] [Copy/Import last published version] Contents are not getting retained in Consent section
#4028 : [SB] Admin is getting navigated to studies list screen when admin clicks on the 'Actions' section or the following copied studies

[v2.0.8] Fixed issue #4024 #4026 #4028

---

Android/app/src/main/java/com/harvard/studyappmodule/NotificationActivity.java
Android/app/src/main/java/com/harvard/usermodule/LoginCallbackActivity.java
Android/app/src/main/java/com/harvard/usermodule/webservicemodel/Profile.java
Android/app/src/main/java/com/harvard/utils/AppController.java
Android/app/src/main/java/com/harvard/utils/realm/RealmMigrationHelper.java

[v2.0.8] Android - issue fix for #3839

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditStudyActiveTask.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp

Fixed issue #4035 : Custom schedule > Issues related to editable fields for studies when viewed from last published version

[v2.0.8] Fixed Issue #4035

---

iOS/MyStudies/MyStudies/AppDelegate.swift
iOS/MyStudies/MyStudies/Controllers/StudyUI/ActivityUI/ActivitiesViewController.swift
iOS/MyStudies/MyStudies/Models/Database/DBHandler.swift
iOS/MyStudies/MyStudies/Models/UserModel/User.swift

[v2.0.8] iOS Fixes for - #4015, #4004

---

common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/model/UserDetailsEntity.java
db-migration/participant-datastore-db-migration/db/migration/V2_0_8__release.sql
participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/beans/ProfileRespBean.java
participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/UserProfileController.java
participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/service/StudiesServicesImpl.java
participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/service/UserManagementProfileServiceImpl.java
participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/service/UserRegistrationServiceImpl.java
participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/util/UserManagementUtil.java
study-datastore/src/main/java/com/hphc/mystudies/dao/AppMetaDataDao.java
study-datastore/src/main/java/com/hphc/mystudies/integration/AppMetaDataOrchestration.java
study-datastore/src/main/java/com/hphc/mystudies/service/StudyMetaDataService.java

Fixed issue #3839: Added verificationTime in /userProfile response to fix this issue

[v2.0.8] Fixed issue #3839

---

iOS/MyStudies/MyStudies/Views/Cells/LineChartCell.swift
iOS/MyStudies/ResearchKit/Common/ORKPasscodeStepViewController.m

[v2.0.8] iOS Fixes for - #4036, #4001

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/consentReviewAndEConsentPage.jsp

#4041 Issue fixed : E-consent steps > Consent document tab > Success toast message issue

[v2.0.8] Fixed issue #4041

---

iOS/MyStudies/MyStudies/Controllers/GatewayUI/ChangePasswordViewController.swift
iOS/MyStudies/MyStudies/Controllers/LoginRegisterUI/LoginUI/ForgotPasswordViewController.swift
iOS/MyStudies/MyStudies/Controllers/LoginRegisterUI/RegisterUI/SignUpViewController.swift
iOS/MyStudies/MyStudies/Storyboards/Gateway.storyboard

[v2.0.8] iOS Fixes for - #3444

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/loginPage.jsp

#4051 : [SB] Password help screen > Admin is not navigating to the sign in screen when clicks on Customer logo

[v2.0.8] Fixed issue #4051

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/instructionsStep.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp

Fixed issue 
#4055, [SB] [UI] Questionnaires > Image choice > Length of the text fields should be the same in both Question step and Form step
#4054, [SB] Questionnaires > Instruction step > Validation message

[v2.0.8] Fixed Issue #4054 and #4055

---

participant-manager/src/app/site-coordinator/mobile-menu/mobile-menu.component.html
participant-manager/src/app/site-coordinator/sitecoordinator.component.html

#4056 : [PM] My account tab > Text change is required

[v2.0.8] Fixed issue #4056

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/templates/copyright.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewSpatialStudyActiveTask.jsp

[v2.0.8] Fixed issues #4048 #4060 #4061

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/NotificationDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp

[v2.0.8] Fixed Issue #4050 #4068

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/changeExpiredPassword.jsp

Fixed issue #4119 : Password field validation

[v2.0.8] Fixed issue #4119

---

iOS/MyStudies/MyStudies/Controllers/GatewayUI/ProfileViewUI/ProfileViewController.swift
iOS/MyStudies/MyStudies/Controllers/GatewayUI/Resource/GatewayResourcesListViewController.swift
iOS/MyStudies/MyStudies/Controllers/GatewayUI/SlideMenu/LeftMenuViewController.swift
iOS/MyStudies/MyStudies/Controllers/StudyUI/ResourceUI/ResourcesViewController.swift
iOS/MyStudies/MyStudies/Models/Database/DBHandler.swift
iOS/MyStudies/MyStudies/Utils/Resources/Localizable/LocalizableString.swift
iOS/MyStudies/MyStudies/Views/Cells/TableView/Resource/ResourcesListCell.swift

Fixes - #4064 #4067 #4025 #4049 #4063

[v2.0.8] iOS Fixes for - 4064, 4067,4025, 4049, 4063

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/LoginServiceImpl.java

#4075 : [SB] Password authentication > Validation message is incorrectly displayed on choosing 4 unique characters for new password .

[v2.0.8] Fixed issue #4075

---

participant-manager/src/app/site-coordinator/mobile-menu/mobile-menu.component.ts

#3885 : [PM] Search bar > Customer logo > Responsive issue

[v2.0.8] Fixed issue #3885 

---

study-datastore/pom.xml

Study Datastore Build failure issue fix due to dependency conflicts

Study Datastore Build failure issue fix due to dependency conflicts

---

Android/app/src/main/java/com/harvard/storagemodule/DbServiceSubscriber.java

[v2.0.8] Android - minor fix for app management

---

auth-server/oauth-scim-service/src/main/java/com/google/cloud/healthcare/fdamystudies/oauthscim/controller/UserController.java
participant-datastore/user-mgmt-module/user-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/filter/TokenIntrospectionFilter.java
participant-manager/src/app/http-interceptors/auth.interceptor.ts
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/AppController.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/AppDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyServiceImpl.java

#4187 - Created study is not getting displayed in the PM

[v2.0.8] [SB] Manage apps Fixes for -  #4187

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/basicInformation.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/addOrEditUserPage.jsp

Fixed Issue #4182  - UI Issue in Study information Screen and Add admin Screen

[v2.0.8] [SB] Fixed Issue #4182

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/UsersController.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/UsersDAO.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/UsersDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/UsersService.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/UsersServiceImpl.java
study-builder/fdahpStudyDesigner/src/main/resources/messageResource.properties
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/addOrEditUserPage.jsp

Fixed Issues #4115 - 'Delete admin' icon is added for the admins who's account is not activated.

[v2.0.9] [SB]Fixed issue #4115

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyList.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/addOrEditUserPage.jsp

Fixed issue #4232 : [SB] Radio buttons and plus icon beside select and add apps / studies in assigned permission is getting enabled for the below scenario
Fixed issue #4166 : [SB] Full stop should be removed at the end of place holder text.

[v2.0.9] Fixed issue #4232 and #4166

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/addOrEditUserPage.jsp

Fixed Issue #4224 -[SB] Edit study admin > Assigned permission > Manage studies >'All items are already selected' text is now 
displaying when all the studies are already added from the dropdown(Select and add studies dropdown).

[v2.0.9] [SB]Fixed issue #4224

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAO.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyService.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyServiceImpl.java
study-builder/fdahpStudyDesigner/src/main/resources/messageResource.properties
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyList.jsp

Fixed Issue #4254  -[SB] Studies list screen > Delete icon is Placed for the studies which are in Prelaunch status

[v2.0.9] [SB]Fixed issue #4254

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyList.jsp

Fixed Issues-#4253 - Studies list screen > Copy_into_new icon > Added mouse hovered text for Copy_into_new icon

[v2.0.9] [SB]Fixed issue #4253

---

study-builder/fdahpStudyDesigner/src/main/resources/application.properties

fixed-issue #4255 - Version in footer is showing as v2.0.7 in the Study Builder dev instance changed to v2.0.8

[v2.0.9] [SB]Fixed issue #4255

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/signUpPage.jsp

Fixed issue - #4290, UI issue in the set up your study builder account screen -Error message text now displaying below the checkbox.

[v2.0.9] [SB]Fixed issue #4290

---

Android/app/src/main/java/com/harvard/studyappmodule/custom/question/CustomDateQuestionBody.java
Android/app/src/main/res/values/strings.xml

[v2.0.9] Android - issue fix for #4249

---

Android/app/src/fda/java/com/harvard/studyappmodule/StudyActivity.java
Android/app/src/main/java/com/harvard/studyappmodule/SurveyActivity.java

[v2.0.9] Android - issue Fix for #4225

---

Android/app/src/fda/java/com/harvard/studyappmodule/StudyActivity.java
Android/app/src/main/java/com/harvard/FdaApplication.java
Android/app/src/main/java/com/harvard/SplashActivity.java
Android/app/src/main/java/com/harvard/studyappmodule/ChangePasswordActivity.java
Android/app/src/main/java/com/harvard/studyappmodule/DeleteAccountActivity.java
Android/app/src/main/java/com/harvard/studyappmodule/ProfileFragment.java
Android/app/src/main/java/com/harvard/studyappmodule/SurveyActivity.java
Android/app/src/main/java/com/harvard/usermodule/VerificationStepActivity.java
Android/app/src/main/java/com/harvard/utils/ActiveTaskService.java
Android/app/src/main/java/com/harvard/utils/AppController.java
Android/app/src/main/java/com/harvard/utils/SharedPreferenceHelper.java
Android/app/src/main/java/com/harvard/utils/realm/RealmEncryptionHelper.java

[v2.0.9] Android - issue Fix for #4033

---

Android/app/build.gradle
Android/app/src/main/AndroidManifest.xml
Android/app/src/main/java/com/harvard/studyappmodule/custom/question/ContinuousScaleQuestion.java
Android/app/src/main/java/com/harvard/studyappmodule/custom/question/ScaleQuestion.java
Android/app/src/main/java/com/harvard/studyappmodule/custom/question/ScaleTextQuestion.java
Android/app/src/main/res/layout/seekbar_horizontal_layout.xml
Android/app/src/main/res/layout/seekbar_text_vertical_layout.xml
Android/app/src/main/res/layout/seekbar_vertical_layout.xml

[v2.0.9] Android - issue Fix for #4244

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyActiveTasksDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditStudyActiveTask.jsp

Fixed Issue #4268 -[SB] Active task > Resolved the duplicate active tasks  which was getting created in the following scenario.

[v2.0.9] [SB]Fixed issue #4268

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditStudyActiveTask.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp

Fixed issue #4053 - Issue related to anchor date based custom scheduling, validation messages are displaying for anchor date and start time fields after clicking done button.

[v2.0.9] [SB]Fixed issue #4053

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerUtil.java

Fixed issue #4256 - Questionnaires > Text response type > Validations are proper in the following scenarios.
1.Allow > All characters > except ? and / > in mobile app accepting other characters >only for ?,/> showing 'Invalid input. Please try again'
2.Disallow > All characters > except ? and / > In mobile app,  accepting / and ? > for other characters showing 'Invalid input. Please try again'

[v2.0.9] [SB]Fixed issue #4256

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyQuestionnaireDAOImpl.java

Fixed issue #4258 - Questionnaires are  getting saved in the draft status.

[v2.0.9] [SB]Fixed Issue- #4258

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyActiveTasksDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/util/FdahpStudyDesignerUtil.java

#4363 : [SB] Active task > Deleted Active task again getting displayed in the active task section 
#4359 : [SB] Import > JPEG format images uploaded in a study fails to import.

[v2.0.10][SB] Fixed issue #4363, #4359

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewFetalStudyActiveTask.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewSpatialStudyActiveTask.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewTowerStudyActiveTask.jsp

[v2.0.10] [SB] Fixed issue#4355 and #4354

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java

#4340 : [SB] Study list screen > When clicked on edit icon > Navigating to first screen of the study list screen

[v2.0.10][SB] Fixed issue #4340

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/basicInformation.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/overViewPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp

Fixed issue - #4360 -  Information icon text has updated wherever image uploaded functionality available in the platform.

[SB] Fixed issue - #4360

---

common-modules/common-service/pom.xml
participant-datastore/consent-mgmt-module/consent-mgmt/pom.xml
participant-datastore/enroll-mgmt-module/enroll-mgmt/pom.xml
participant-datastore/user-mgmt-module/user-mgmt/pom.xml
study-builder/fdahpStudyDesigner/pom.xml
study-datastore/pom.xml

Bump log4j-core and log4j-api  updated from 2.16.0 to 2.17.1 in /participant-datastore/user-mgmt-module/user-mgmt, /participant-datastore/enroll-mgmt-module/enroll-mgmt ,
/participant-datastore/consent-mgmt-module/consent-mgmt.

[SB] Bumps Issue Fix 

---

iOS/MyStudies/MyStudies/AppDelegate.swift
iOS/MyStudies/MyStudies/Models/Activity/Activity.swift
iOS/MyStudies/MyStudies/Models/Database/DBActivity.swift
iOS/MyStudies/MyStudies/Models/Database/DBHandler.swift
iOS/MyStudies/MyStudies/Utils/Extension/Date+Extensions.swift
iOS/MyStudies/MyStudies/Utils/Extension/String+Extensions.swift
iOS/MyStudies/MyStudies/Utils/Helpers/AnchorDateHandler.swift
iOS/MyStudies/MyStudies/Utils/Helpers/Managers/LocalNotification.swift
iOS/MyStudies/MyStudies/Utils/Utilities.swift
iOS/MyStudies/MyStudies/Views/Cells/TableView/Activity/ActivitiesTableViewCell.swift

[v2.0.10] iOS Fixes for -timezone issue

---

iOS/MyStudies/MyStudies/Controllers/StudyUI/ActivityUI/ActivitiesViewController.swift
iOS/MyStudies/MyStudies/Views/UIViews+Additions/ComprehensionFailureUI/ComprehensionFailure.swift

Fixes - Issues - #4179 , #4267

[v2.0.10] iOS Fixes for - 4179, 4267

---

Android/app/build.gradle
Android/app/src/main/java/com/harvard/SplashActivity.java
Android/app/src/main/java/com/harvard/studyappmodule/ConsentCompletedActivity.java
Android/app/src/main/java/com/harvard/studyappmodule/GatewayResourcesWebViewActivity.java
Android/app/src/main/java/com/harvard/studyappmodule/PdfDisplayActivity.java
Android/app/src/main/java/com/harvard/studyappmodule/ResourcesWebViewActivity.java
Android/app/src/main/java/com/harvard/studyappmodule/SurveyActivitiesFragment.java
Android/app/src/main/java/com/harvard/utils/AppController.java
Android/app/src/main/java/com/harvard/utils/PdfViewerView.java
Android/app/src/main/res/drawable/default_dot.xml
Android/app/src/main/res/drawable/selected_dot.xml
Android/app/src/main/res/drawable/tab_selector.xml
Android/app/src/main/res/layout/activity_pdfdisplay.xml
Android/app/src/main/res/layout/activity_pdfgeneration.xml
Android/app/src/main/res/layout/activity_resources_web_view.xml
Android/app/src/main/res/layout/pdfdisplayview.xml

realm instance optimized and changed the pdf lib (reduced the apk size 16mb) removed the support for KitKat version to support pdf change

[v2.0.10] Android - fix #4300

---

Android/app/src/fda/java/com/harvard/studyappmodule/StudyActivity.java
Android/app/src/main/java/com/harvard/studyappmodule/NotificationListAdapter.java

[v2.0.10] Android - fix #4270

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/userPasswordReset.jsp

issue #4418 - When clicked on account creation link, Getting correct screen for after deactivating new admin in SB.

[SB] issue_#4418

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/addOrEditUserPage.jsp

Fixed issue #4421 - click on edit study admin ,while adding some more apps and studies ,radio buttons alignment are displaying correct in SB.

[SB] issue_#4421

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp

#4451 : [SB] Study Activities section > Schedule tab > Custom schedule > UI issue

[v2.0.10] [SB] Fixed issue #4451

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/errorPage.jsp

Fixed Issue #4418 - When clicked on account creation link, Getting correct screen and getting correct message for after deactivating new admin in SB.

[SB] Reopened_Issue_#4418

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyActiveTasksDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditStudyActiveTask.jsp

Duplicate Issue - In Active tasks section ,after selecting active task from the dropdown, again change the active task from the dropdown and fill the data and after Done ,only one active task is created in SB.

[SB] Duplicate Issue

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/formStep.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp

Fixed issue 
#4373 , [SB] Active task > Anchor date > UI issue is observed in the custom scheduling type
#4425, [SB] Questionnaires > Form step > 'Anchor date' cannot be used when questions are added with 'Repeatable' type of form

[v2.0.10] [SB] Fixed issue #4448 and #4425

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyEligibilty.jsp
study-datastore/src/main/java/com/hphc/mystudies/dto/StudyVersionDto.java

Fixed Issue 
#4446, [SB] Eligibility section can not be marked as complete
#4275, [Unknown backend] Newly created activities are not getting displayed in 'Study activities' list screen

[v2.0.10] [SB][SD] Fixed Issue #4446 and #4275

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp

#4454 [SB] UI issue is observed in the study activities section for the below scenario

[v2.0.10][SB] Fixed issue #4454

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyExportImportService.java

#4379 : 
[SB][Copy][Import] Branching logic mismatch for Questionnaire with text choice questions

[v2.0.10][SB] Fixed issue #4379

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp

#4484 -  add multiple questions in questions steps and add a text choice response question [add 2 choices including 'other option'],enter all the fields and click on done ,apply branching and for text choice questions select the destination steps and click on Done, now  selected value are getting saved

Fixed issue #4484

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/signUpPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/addOrEditUserPage.jsp

Fixed issue #4397 - error message is not displayed for phone number field in set up account screen.

Fixed issue #4397

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/AppDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyQuestionnaireDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/scheduler/FDASchedulerService.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/scheduler/MoveCloudStorageSchedulerService.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyExportImportService.java

Fixed issue #4509 : Aborted connection to database fda_hphc

[v2.0.10][SB] #4509 Issue fixed

---

Android/app/src/main/java/com/harvard/passcodemodule/PasscodeSetupActivity.java
Android/app/src/main/java/com/harvard/studyappmodule/SurveyActivity.java

[v2.0.10] Android - #4453, #4428

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionStep.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyEligibilty.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/addOrEditUserPage.jsp

#4429, #4281, #4416 issue resolved

#4429, #4281, #4416 issue resolved

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/addOrEditUserPage.jsp

[SB] Edit admin screen >'Enforce password change' button is now displaying in the mentioned scenario.

[v2.0.10] Issue fixes #4417

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyQuestionnaireDAOImpl.java

Fixed issue 
[SB] Add/edit study > Add/edit questionnaires > Not able to add any questionnaire steps in the following scenario #4536

[v2.0.10]Fixed issue #4536

---

.github/workflows/lint-android.yml
Android/app/src/main/java/com/harvard/studyappmodule/CustomActivitiesDailyDialogClass.java
Android/app/src/main/java/com/harvard/studyappmodule/ResourcesWebViewActivity.java
Android/app/src/main/java/com/harvard/studyappmodule/consent/ConsentDocumentStepLayoutCustom.java
Android/app/src/main/java/com/harvard/utils/PdfViewerView.java
iOS/MyStudies/MyStudies/Controllers/StudyUI/ActivityUI/ActivitiesViewController.swift

- Fixes Issues https://github.com/GoogleCloudPlatform/fda-mystudies/issues/4501 https://github.com/GoogleCloudPlatform/fda-mystudies/issues/4526 https://github.com/GoogleCloudPlatform/fda-mystudies/issues/4518 https://github.com/GoogleCloudPlatform/fda-mystudies/issues/4279

[v2.0.10] Android and iOS -#4501,#4526,#4518,#4279 

---

iOS/MyStudies/MyStudies/Controllers/GatewayUI/StudyUI/StudyListViewController.swift

Fixes 3rd scenarios of - #4270

[v2.0.10] iOS - #4270

---

iOS/MyStudies/MyStudies/AppDelegate.swift

Fixes 1st scenarios of - https://github.com/GoogleCloudPlatform/fda-mystudies/issues/4270

[v2.0.10] iOS - #4270 notification issue

---

study-datastore/src/main/java/com/hphc/mystudies/dao/AppMetaDataDao.java
study-datastore/src/main/java/com/hphc/mystudies/dto/NotificationDto.java

#4549 : [iOS] [QA]Notification list > Notifications are not getting displayed in the notifications list

[2.0.10][SD]#4549 issue fix

---

auth-server/oauth-scim-service/src/main/resources/templates/login.html
participant-manager/src/assets/css/root.scss
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/users/addOrEditUserPage.jsp

[SB] [PM] [QA] Add admin screen > Dropdown icon is getting displayed in the email field #4545
[[iOS] Sign in screen > UI issue](https://github.com/GoogleCloudPlatform/fda-mystudies/issues/4257#)
#4257
[Mobile Apps] UI issue in the sign in screen of the mobile apps #4349

Fixed issues #4545 #4257 and #4349

---

auth-server/oauth-scim-service/src/main/resources/templates/login.html
deployment/kubernetes/ingress.yaml
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyQuestionnaireDAOImpl.java
study-builder/fdahpStudyDesigner/src/main/resources/application.properties
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/apps/appActionListPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/actionListPage.jsp
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/studyList.jsp

[[SB] Add/edit study > Add/edit questionnaires > Not able to add any questionnaire steps in the following scenario] #4536
[[iOS] Sign in screen > UI issue]#4257

[V2.0.10]Develop issue fixes

---

study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/bo/UserPermissions.java
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/ApplicationContext.xml

#4564 : [2.0.10][SB] Db migration issue in V2_0_6__release.sql after Spring version upgradation

#4564 Issue fixed

---

documentation/whats-new.md
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/bo/UserPermissions.java
study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/ApplicationContext.xml

Solved below issues:
- Db migration issues fix in Studybuilder app
- Update in What's new document

Minor fixes on 2.0. 10 develop version

---

iOS/MyStudies/MyStudies/AppDelegate.swift
iOS/MyStudies/MyStudies/Controllers/ConsentUI/ConsentSharePdfStepViewController.swift
iOS/MyStudies/MyStudies/Controllers/StudyUI/ActivityUI/ActivitiesViewController.swift
iOS/MyStudies/MyStudies/Controllers/StudyUI/ResourceUI/ResourcesViewController.swift
iOS/MyStudies/MyStudies/Models/Database/DBHandler.swift
iOS/MyStudies/MyStudies/Models/Database/DBStudy.swift
iOS/MyStudies/MyStudies/Models/UserModel/User.swift
iOS/MyStudies/MyStudies/Networking/APIs/WCPServices.swift

- ios consent signature

---

iOS/MyStudies/MyStudies/AppDelegate.swift
iOS/MyStudies/MyStudies/Controllers/ConsentUI/ConsentSharePdfStepViewController.swift
iOS/MyStudies/MyStudies/Controllers/GatewayUI/StudyUI/StudyListViewController.swift
iOS/MyStudies/MyStudies/Controllers/StudyUI/ActivityUI/ActivitiesViewController.swift
iOS/MyStudies/MyStudies/Models/Database/DBHandler.swift
iOS/MyStudies/MyStudies/Models/StudyModel/Study.swift

iOS consent issues

---

iOS/MyStudies/MyStudies/Controllers/SplashViewController.swift
iOS/MyStudies/MyStudies/Controllers/StudyUI/ActivityUI/ActivitiesViewController.swift
iOS/MyStudies/MyStudies/Controllers/StudyUI/StudyDashboardUI/StudyDashboardTabbarViewController.swift
iOS/MyStudies/MyStudies/Controllers/StudyUI/StudyOverviewUI/StudyHomeViewController.swift
iOS/MyStudies/MyStudies/Networking/APIs/ConsentServices.swift

- ios consent issue 4760, 4727

---

iOS/MyStudies/MyStudies/Utils/Extension/String+Extensions.swift

iOS code clean up

---

iOS/MyStudies/MyStudies.xcodeproj/project.pbxproj

- ios build issues

---

iOS/MyStudies/MyStudies/AppDelegate.swift
iOS/MyStudies/MyStudies/Controllers/EligibilityUI/EligibilityStepViewController.swift
iOS/MyStudies/MyStudies/Controllers/GatewayUI/StudyUI/StudyListViewController.swift
iOS/MyStudies/MyStudies/Controllers/SplashViewController.swift
iOS/MyStudies/MyStudies/Controllers/StudyUI/ActivityUI/ActivitiesViewController.swift

- ios issue 4793, 4792

---

iOS/MyStudies/MyStudies.xcodeproj/project.pbxproj
iOS/MyStudies/MyStudies/AppDelegate.swift
iOS/MyStudies/MyStudies/Controllers/EligibilityUI/EligibilityStepViewController.swift
iOS/MyStudies/MyStudies/Controllers/GatewayUI/StudyUI/StudyListViewController.swift
iOS/MyStudies/MyStudies/Controllers/SplashViewController.swift
iOS/MyStudies/MyStudies/Controllers/StudyUI/ActivityUI/ActivitiesViewController.swift

- iOS Repo sync issue 4793, 4792

---

iOS/MyStudies/MyStudies/AppDelegate.swift
iOS/MyStudies/MyStudies/Controllers/EligibilityUI/EligibilityStepViewController.swift
iOS/MyStudies/MyStudies/Controllers/GatewayUI/StudyUI/StudyListViewController.swift
iOS/MyStudies/MyStudies/Controllers/SplashViewController.swift
iOS/MyStudies/MyStudies/Controllers/StudyUI/ActivityUI/ActivitiesViewController.swift

- iOS Repo sync issue 4793, 4792 

---

iOS/MyStudies/MyStudies/Controllers/EligibilityUI/EligibilityStepViewController.swift
iOS/MyStudies/MyStudies/Controllers/GatewayUI/StudyUI/StudyListViewController.swift
iOS/MyStudies/Pods/Realm/Realm/RLMObjectStore.mm
iOS/MyStudies/Pods/Realm/include/RLMObject_Private.hpp

- ios issue notification

---

Android/app/src/main/java/com/harvard/studyappmodule/StandaloneActivity.java
Android/app/src/main/java/com/harvard/studyappmodule/StandaloneStudyInfoActivity.java
Android/app/src/main/java/com/harvard/studyappmodule/StudyFragment.java
Android/app/src/main/java/com/harvard/studyappmodule/StudyInfoActivity.java
Android/app/src/main/java/com/harvard/studyappmodule/consent/CustomConsentViewTaskActivity.java

repo sync for one issue from android

#4651 issue fixe

---

Android/app/src/main/java/com/harvard/studyappmodule/StandaloneActivity.java
Android/app/src/main/java/com/harvard/studyappmodule/StandaloneStudyInfoActivity.java
Android/app/src/main/java/com/harvard/studyappmodule/StudyFragment.java
Android/app/src/main/java/com/harvard/studyappmodule/StudyInfoActivity.java
Android/app/src/main/java/com/harvard/studyappmodule/consent/CustomConsentViewTaskActivity.java

Copy st develop android

---

iOS/MyStudies/MyStudies/AppDelegate.swift
iOS/MyStudies/MyStudies/Controllers/GatewayUI/StudyUI/StudyListViewController.swift
iOS/MyStudies/MyStudies/Controllers/SplashViewController.swift
iOS/MyStudies/MyStudies/Networking/APIs/EnrollServices.swift

- ios issue 4649

---

iOS/MyStudies/MyStudies/AppDelegate.swift
iOS/MyStudies/MyStudies/Controllers/GatewayUI/StudyUI/StudyListViewController.swift
iOS/MyStudies/MyStudies/Controllers/SplashViewController.swift

- ios notification issue 2

---

iOS/MyStudies/MyStudies/Controllers/GatewayUI/StudyUI/StudyListViewController.swift

ios notification issue

---

iOS/MyStudies/MyStudies/AppDelegate.swift
iOS/MyStudies/MyStudies/Controllers/StudyUI/ActivityUI/QuestionStepController/TextChoiceQuestionController.swift
iOS/MyStudies/MyStudies/Controllers/StudyUI/StudyOverviewUI/StudyHomeViewController.swift
iOS/MyStudies/MyStudies/Models/Database/DBHandler.swift
iOS/MyStudies/MyStudies/Views/Steps/ActivityStep/ActivityStepResultModel/ActivityStepResult.swift

iOS issue 4810

---

iOS/MyStudies/MyStudies/Views/Steps/ActivityStep/ActivityQuestionStep.swift

iOS issue 4839

---

iOS/MyStudies/MyStudies/Controllers/StudyUI/ActivityUI/QuestionStepController/TextChoiceQuestionController.swift
iOS/MyStudies/MyStudies/Models/Database/DBHandler.swift
iOS/MyStudies/ResearchKit/Common/ORKTextChoiceCellGroup.m

iOS issue multiple choice

---

iOS/MyStudies/MyStudies/AppDelegate.swift
iOS/MyStudies/MyStudies/Controllers/StudyUI/StudyOverviewUI/StudyHomeViewController.swift
iOS/MyStudies/ResearchKit/Common/ORKStepViewController.m
iOS/MyStudies/ResearchKit/Common/ORKTaskViewController.m
iOS/MyStudies/ResearchKit/Consent/ORKConsentReviewController.m
iOS/MyStudies/ResearchKit/Consent/ORKConsentReviewStepViewController.m
iOS/MyStudies/ResearchKit/Consent/ORKVisualConsentStepViewController.m

Ios build issue

---

iOS/MyStudies/MyStudies/AppDelegate.swift
iOS/MyStudies/MyStudies/Controllers/StudyUI/StudyOverviewUI/StudyHomeViewController.swift
iOS/MyStudies/MyStudies/Utils/Helpers/Constants/Constants.swift
iOS/MyStudies/ResearchKit/Common/ORKStepViewController.m
iOS/MyStudies/ResearchKit/Common/ORKTaskViewController.m
iOS/MyStudies/ResearchKit/Consent/ORKConsentReviewController.m
iOS/MyStudies/ResearchKit/Consent/ORKConsentReviewStepViewController.m
iOS/MyStudies/ResearchKit/Consent/ORKVisualConsentStepViewController.m

iOS build issues

---

iOS/MyStudies/MyStudies/Controllers/StudyUI/ActivityUI/ActivitiesViewController.swift

iOS issue activity update

---

iOS/MyStudies/ResearchKit/Common/ORKAnswerFormat.h
iOS/MyStudies/ResearchKit/Common/ORKAnswerFormat.m
iOS/MyStudies/ResearchKit/Consent/ORKConsentSharingStep.m

iOS issue 4889

---

iOS/MyStudies/MyStudies/AppDelegate.swift
iOS/MyStudies/MyStudies/Controllers/StudyUI/ActivityUI/ActivitiesViewController.swift
iOS/MyStudies/MyStudies/Networking/APIs/ConsentServices.swift
iOS/MyStudies/MyStudies/Views/Steps/ActivityStep/ActivityQuestionStep.swift
iOS/MyStudies/ResearchKit/Common/ORKQuestionStepViewController.m
iOS/MyStudies/ResearchKit/Common/ORKTextChoiceCellGroup.m

iOS issue 4896, 4893

---

db-migration/participant-datastore-db-migration/db/migration/V2_0_11__release.sql
db-migration/response-datastore-db-migration/db/migration/V2_0_11__release.sql
db-migration/study-builder-db-migration/db/migration/V2_0_11_release.sql
response-datastore/response-server-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/ActivityResponseProcessorServiceImpl.java
study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/dao/StudyDAOImpl.java

Backend repo synk , dev env to st-develop

Backend repo synk , dev env to st-develop

---

iOS/MyStudies/MyStudies/Controllers/SplashViewController.swift
iOS/MyStudies/MyStudies/Controllers/StudyUI/ActivityUI/ActivitiesViewController.swift
iOS/MyStudies/MyStudies/Controllers/StudyUI/StudyOverviewUI/StudyHomeViewController.swift
iOS/MyStudies/MyStudies/Networking/APIs/ResponseServices.swift
iOS/MyStudies/MyStudies/Networking/APIs/WCPServices.swift
iOS/MyStudies/MyStudies/Networking/Network setup/NetworkManager.swift
iOS/MyStudies/MyStudies/Networking/Network setup/NetworkWebServiceHandler.swift
iOS/MyStudies/MyStudies/Utils/Helpers/SyncUpdate/SyncUpdate.swift
iOS/MyStudies/MyStudies/Views/Cells/TableView/Activity/ActivitiesTableViewCell.swift

iOS issues offline

---

iOS/MyStudies/MyStudies/AppDelegate.swift
iOS/MyStudies/MyStudies/Controllers/StudyUI/ActivityUI/ActivitiesViewController.swift
iOS/MyStudies/MyStudies/Networking/APIs/ResponseServices.swift
iOS/MyStudies/MyStudies/Networking/Network setup/NetworkWebServiceHandler.swift

iOS issue 4912

---

iOS/MyStudies/MyStudies/Controllers/LoginRegisterUI/LoginUI/SignInViewController.swift

iOS issue 4910

---

iOS/MyStudies/ResearchKit/Consent/ORKConsentDocument.m

iOS issue 4941

---

iOS/MyStudies/MyStudies/Controllers/LoginRegisterUI/LoginUI/SignInViewController.swift
iOS/MyStudies/ResearchKit/Consent/ORKConsentDocument.m

iOS repo sync

---

iOS/MyStudies/MyStudies/Utils/Helpers/RepeatableFormStep/RepeatableFormStepViewController.m

iOS Issue 4977

---

iOS/MyStudies/MyStudies/Views/Steps/ActivityStep/ActivityResultModel/ActivityResult.swift
iOS/MyStudies/MyStudies/Views/Steps/ActivityStep/ActivityStepResultModel/ActivityStepResult.swift
iOS/MyStudies/ResearchKit/Common/ORKStepViewController.h
iOS/MyStudies/ResearchKit/Common/ORKStepViewController.m

iOS issue 4987

---

study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/overViewPage.jsp

Fixed issue#4993

---

iOS/MyStudies/MyStudies/Views/Steps/ActivityStep/ActivityStepResultModel/ActivityStepResult.swift

iOS issue 5011

---

iOS/MyStudies/MyStudies/Networking/APIs/ResponseServices.swift

iOS chart issue

---

.github/workflows/build-iOS.yml

-ios build issue
