- study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/addOrEditResourcePage.jsp
Fixed issue #2661 [Mobile] Html breaking in Resources Text.
Converting the HTML tag to text was causing the issue in mobile app.
HTML tags were getting saved as text format `&lt;p&gt;btc&lt;b&gt;`, so removed those piece of code.
Screenshot after fix:
> Fixed issue #2661 [Mobile] Html breaking in Resources Text 

- response-datastore/tf-deployment.yaml
Terraform deployment for Response Datastore does not use the correct node port path for Enroll Service. Updated this value and tested. This resolves #2339 and I have confirmed that response data is now correctly showing in Firestore.
> Fix for 2339

- auth-server/oauth-scim-service/src/main/java/com/google/cloud/healthcare/fdamystudies/oauthscim/common/AuthScimConstants.java
- auth-server/oauth-scim-service/src/main/java/com/google/cloud/healthcare/fdamystudies/oauthscim/controller/CallbackController.java
- auth-server/oauth-scim-service/src/main/java/com/google/cloud/healthcare/fdamystudies/oauthscim/controller/LoginController.java
- auth-server/oauth-scim-service/src/main/resources/static/css/style.css
- auth-server/oauth-scim-service/src/main/resources/templates/autoLogin.html
- auth-server/oauth-scim-service/src/main/resources/templates/consent.html
- auth-server/oauth-scim-service/src/main/resources/templates/error.html
Fixed issues #2325, #2852 and #2820:
1. [Hydra - Mobile apps] [Audit Logs] "appVersion" is displayed null for the events #2820
Fix: Setting `appVersion` in cookie and then setting the value in `AuditEventMapper.fromHttpServletRequest(request)`.
2. Make oauth server login screens error toasts more visible #2325
Fix: Shifted the error message in the middle of the screen. Displaying error message to 5 second was already fixed in last release.
3. Text size of the loader page should be increased #2852
Fix: Removed `font-size` from `child_text ` class, as using `font-size` from `loading_text` class.
> Fixed issues #2325, #2852 and #2820, oauth server- audit logs and UI issues

- study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/errorPage.jsp
- study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/fdaAdminDashBoardPage.jsp
Fixed issue #2304
Changed the errorPage text to `This link is no longer valid to be used. For any assistance needed with your account, please contact the system admin.`
> Study Builder : Fixed UI issue #2304 by changing the text when activation link is invalid/expired

- auth-server/oauth-scim-service/src/main/java/com/google/cloud/healthcare/fdamystudies/oauthscim/common/CookieHelper.java
- auth-server/oauth-scim-service/src/main/java/com/google/cloud/healthcare/fdamystudies/oauthscim/controller/UserController.java
- auth-server/oauth-scim-service/src/main/java/com/google/cloud/healthcare/fdamystudies/oauthscim/service/UserServiceImpl.java
- auth-server/oauth-scim-service/src/test/java/com/google/cloud/healthcare/fdamystudies/oauthscim/controller/UserControllerTest.java
1) Fixed issue #2827 [Hydra][Audit logs] Event triggered in wrong scenario
- Moved `PASSWORD_RESET_SUCCEEDED` event from password_reset API to password_change API.
- Logging this event after validating users account status, when user completes password reset process.
- Fixed test case failure.
2) Fixed issue #1248 Sign in not available page is continuously causing issue for sign in
Fix: Since cookie age was 10 minutes, so data in cookie was getting null after 10 minutes and app was redirecting to error page.
Increased the cookie age to 30 minutes.
> Fixed issues #2827 [Hydra][Audit logs] Event triggered in wrong scenario and #1248 

- auth-server/oauth-scim-service/src/main/resources/static/js/autoLogin.js
- auth-server/oauth-scim-service/src/main/resources/static/js/consent.js
Fixed issues:
1. [Android] Continuous loading animator and fails to navigate to app when internet is disrupted during sign in #1150
2. Mobile app sign-in hangs indefinitely #2421
Fix: Reduced the wait time and used `setInterval `function instead of `setTimeout `, which will keep on trying after specified interval, if there is any network issue happened in between.
> Fixed issues #1150 and #2421 [oauth server]  Continuous loading animator and fails to navigate to app when internet is disrupted during sign in

- auth-server/oauth-scim-service/src/main/resources/templates/error.html
- Fixed issue #2922 [PM] Adjust the space between the icon and the text 
- Removed `margin-top` from css text class for error page to remove the extra space between error image and text.
> Fixed issue #2922 [PM] Adjust the space between the icon and the text 

- participant-datastore/enroll-mgmt-module/enroll-mgmt/src/main/java/com/google/cloud/healthcare/fdamystudies/controller/EnrollmentTokenController.java
- participant-datastore/enroll-mgmt-module/enroll-mgmt/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/tests/EnrollmentTokenControllerTest.java
Changed HTTP status code for /validateEnrollmentToken endpoint for token already used. Issue #2923 fix.
> [Participant Enroll Datastore] Changed HTTP status code for /validateEnrollmentToken endpoint for token already used

- common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/repository/ParticipantEnrollmentHistoryRepository.java
- common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/repository/StudyRepository.java
- participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/mapper/ParticipantMapper.java
- participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/StudyServiceImpl.java
- participant-manager-datastore/participant-manager-service/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/StudyControllerTest.java
Fixed issue #2423: 
- Written a query in `ParticipantEnrollmentHistoryRepository` to get the enrollment status based on created_time DESC
- Added conditional check to send enrollment status as withdrawn when participant fails eligibility test post withdrawn for open study
- Removed shouldNotReturnRegisteredParticipantWithYetToJoinStudyStatus() test as this is not a valid scenario as per current requirement
> Participant Manager Datastore: Fixed issue #2423

- auth-server/oauth-scim-service/src/main/resources/static/js/autoLogin.js
- auth-server/oauth-scim-service/src/main/resources/static/js/consent.js
Fixed issue  Mobile app sign-in hangs indefinitely #2421
Reverting `setInterval` to `setTimeout`, which is causing sign-in screen randomly only in chrome browser.
> Fixed issue  Mobile app sign-in hangs indefinitely #2421

- auth-server/oauth-scim-service/src/main/java/com/google/cloud/healthcare/fdamystudies/oauthscim/controller/UserController.java
- participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/mapper/ParticipantMapper.java
- participant-manager-datastore/participant-manager-service/src/main/java/com/google/cloud/healthcare/fdamystudies/service/StudyServiceImpl.java
Fixed issue #2999 #3000: Added conditional check to send enrollment status as `withdrawn `when participant's enrollment status is `yetToEnroll ` or  `notEligible ` post withdrawn in participant details API
#2989: set  `userId ` in  `auditRequest ` object
> Participant Manager Datastore: Fixed issue #2999 #3000 #2989

- auth-server/oauth-scim-service/src/main/java/com/google/cloud/healthcare/fdamystudies/oauthscim/controller/CallbackController.java
- auth-server/oauth-scim-service/src/main/resources/templates/login.html
- participant-manager-datastore/participant-manager-service/src/test/java/com/google/cloud/healthcare/fdamystudies/controller/SiteControllerTest.java
- participant-manager-datastore/participant-manager-service/src/test/java/com/google/cloud/healthcare/fdamystudies/helper/TestDataHelper.java
- Fixed issue #2882 [Hydra] Account lock functionality is failed in Some scenario
- Issue: Mobile app is throwing error when user tries to reset password using temporary password.
- Fix.: `email` address was missing in deeplink URL. So added `ACCOUNT_LOCKED` validation in `CallbackController.java` file.
- Text changes in `login.html` file as per BA input.
- Modified `SiteControllerTest.java` file to fix build failure of Participant manager datastore.
> Fixed issue #2882 [Hydra] Account lock functionality is failed in Some scenario

- auth-server/tf-deployment.yaml
- deployment/README.md
- deployment/deployment.hcl
- deployment/kubernetes/README.md
- deployment/kubernetes/cert.yaml
- deployment/kubernetes/ingress.yaml
- deployment/mystudies.hcl
- deployment/scripts/create_participant_manager_superadmin.sh
- deployment/scripts/create_study_builder_superadmin.sh
- deployment/scripts/register_clients_in_hydra.sh
- deployment/scripts/set_env_var.sh
- hydra/tf-deployment.yaml
- participant-datastore/consent-mgmt-module/tf-deployment.yaml
- participant-datastore/enroll-mgmt-module/tf-deployment.yaml
- participant-datastore/user-mgmt-module/tf-deployment.yaml
- participant-manager-datastore/tf-deployment.yaml
- participant-manager/Dockerfile
- participant-manager/src/environments/environment.prod.ts
- participant-manager/tf-deployment.yaml
- participant-manager/tf-service.yaml
- response-datastore/tf-deployment.yaml
- study-builder/tf-deployment.yaml
- study-datastore/tf-deployment.yaml
@moschetti 
- We have updated the Terraform deployment scripts similar to the master branch, so that it will be uniform between the branches and Going forward it will be easier to create new environment by using the develop branch in our system.
- We have removed access code from this script (create_study_builder_superadmin.sh), as this field is removed from the study builder database script (HPHC_My_Studies_DB_Create_Script.sql). Otherwise this script will fail to create the Super admin
> Deployment scripts update

- deployment/mystudies.hcl
@moschetti 
As per the discussion in the email, we have whitelisted the images path of new isitio pods and tested the same in our environment.
This patch should fix this issue #3172
> New GKE cluster Isitio system Pods issue

- study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
- study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/questionnaire.jsp
Fixed issue #562 Start time cannot be specified for activity with custom schedule
Issue: Tooltip and message "Select a date range" was getting hidden after user save/Done the questionnaire/active task.
Issue is happening when user switches between regular and anchor date.
Fix: Shifted the complete message section above div, so that it will be visible all the time, while editing and after saving also.
> [v2.0.3] Fixed issue #562 Start time cannot be specified for activity with custom schedule

- participant-datastore/consent-mgmt-module/consent-mgmt/src/main/resources/application.properties
- response-datastore/response-server-service/src/main/resources/application.properties
Changed the _spring.jpa.hibernate.ddl-auto property_ to **none** to fix DB migration script execution failure. 
With the current value "**update**" hibernate manipulate the database schema at startup.
> [v2.0.3] DB migration script execution failure fix for Participant Datastore

- study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/changeExpiredPassword.jsp
- study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/loginPage.jsp
- study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/userPasswordReset.jsp
This PR contains the issue fixes for issue #954  and #3324  .
1. 3324 issue fixes:
==========
- Reset password screen logo changed.
2. 954 issue fixes:
==========
- Change top text to "Your password has expired. Please create a new password."
- Change top text box text to "Previous password"
- Change middle text box text to "New password"
- Change bottom text box text to "Confirm new password"
- The logo in the upper left corner does not link back to the main study builder landing page and the upper
right link says "sign out" which is not correct because I'm not signed on this page - user should not be 
signed in at this point and must be signed out instead and so we need not display sign out here either.
- The confirmation messages that appear after clicking "submit" are displayed for 1 …
> [v2.0.4] Issue 954 and 3324 fixes

- common-modules/common-service/src/main/java/com/google/cloud/healthcare/fdamystudies/common/ErrorCode.java
Wrong Error Message Displayed due to incorrect HTTP Status code. #3440 #3304
> [v2.0.5]Wrong Error Message Displayed due to incorrect HTTP Status code

- deployment/README.md
Fix #3575
Add instructions for setting Shared VPC admin at organization level for Cloud Build service account and remove step for setting this at folder level since that is no longer an option.
> Fix #3575 - Add Cloud Build Shared VPC deployment instructions

- documentation/API/study-datastore/swagger.json
- study-datastore/pom.xml
- study-datastore/src/main/java/com/hphc/mystudies/bean/QuestionnaireStepsBean.java
- study-datastore/src/main/java/com/hphc/mystudies/dao/ActivityMetaDataDao.java
- study-datastore/src/main/java/com/hphc/mystudies/service/StudyMetaDataService.java
- study-datastore/src/main/java/com/hphc/mystudies/util/StudyMetaDataUtil.java
- study-datastore/src/main/java/com/hphc/mystudies/web/servlet/AuthenticationService.java
- study-datastore/src/main/resources/hibernate.cfg.xml
- study-datastore/src/main/webapp/WEB-INF/web.xml
Issue #3125, API documentation using swagger - Study Datastore.
- JSON `documentation/API/study-datastore/swagger.json` file will be created at compile time which user can use in [swagger editor](https://editor.swagger.io/) to view the API documentation of study datastore.
- Added swagger dependencies and upgraded com.sun.jersey to org.glassfish.jersey.
- Added `com.github.kongchen` plugin to generate json file at run time.
- Created `QuestionnaireStepsBean.java` to overcome Jackson circular dependencies for List of Questionnaire steps
> [v2.0.6] Issue #3125, API documentation using swagger - Study Datastore

- study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/comprehensionList.jsp
[SB] Comprehension test > 'Minimum score needed to pass the test' field should be mandatory field #3606
Issue: 'Minimum score needed to pass the test' field; is not a mandatory field so the user is able to do 'Mark as completed' without entering that field
Fix: Added `required` attribute and `data-error="Please fill out this field"` with red star mark to denote this input is required field
> [v2.0.6] Fixed issue #3606 [SB] Comprehension test > 'Minimum score needed to pass the test' field should be mandatory field

- study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/overViewPage.jsp
[SB] View mode of the study > Overview screen > User is able to edit the 'Description' field in view mode #3600
Issue: User is able to edit the summernote editor when multiple editor is added in overview screen. 
Fix: Explicitly disabled all editors by updating `contenteditable` attribute to false, when checking the study in view mode.
> [v2.0.6] Fixed issue #3600 [SB] View mode of the study > Overview screen > User is able to edit the 'Description' field in view mode 

- study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/viewFetalStudyActiveTask.jsp
- study-builder/fdahpStudyDesigner/src/main/webapp/js/common.js
Fixed issue #3745, by changing error message from `The characters like (< >) are not allowed` to `Please use characters from the following set only: A-Z a-z 0-9 *()_+|:.-`
> [v2.0.6] - Fixed issue #3745

- db-migration/study-builder-db-migration/db/migration/V2_0_6__release.sql
- study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/view/study/activeTaskScheduled.jsp
- study-datastore/src/main/java/com/hphc/mystudies/dao/ActivityMetaDataDao.java
- [SB] [QA] Active tasks custom schedule > Three time fields are showing for each custom schedule row and UI is distorted #3797
- [SB] Active tasks > Regular/Anchor based One Time> 'startTime' displaying empty for launch with study option and hence activities are not displaying in mobile apps #3741
> [v2.0.6] Fixed issues #3797 #3741 study builder active tasks custom schedule 

- study-datastore/pom.xml
- study-datastore/src/main/java/com/hphc/mystudies/dao/ActivityMetaDataDao.java
[SB] [Import] Custom schedule > Order of the runs is incorrect in GetStudyActivityList API for imported study hence scheduling in mobile apps is incorrect #3803
Issue :Actual: Order of the runs is incorrect which is causing mobile apps scheduling behave indifferently for imported study
Expected: Order should be same as of original study
> [v2.0.6] Fixed issue 3803

- study-builder/fdahpStudyDesigner/src/main/webapp/WEB-INF/templates/subheader.jsp
#3824: Added return statement to break the function when URL is null.
#3828: Added unescape() instead decodeURIComponent() to fix this issue
> [v2.0.6] Fixed issue #3824 #3828

- deployment/scripts/create_study_builder_superadmin.sh
Fixed issue :
When logged in with default superadmin credentials should force the admin to change password #3173
added one day extra in EXPIRY_DATETIME, to avoid issues related to time zone difference.
> [v2.0.6] Fixed #3173 study builder for the admin to change password

- study-datastore/src/main/java/com/hphc/mystudies/dao/ActivityMetaDataDao.java
Fixed issue
[SB] Active task custom scheduling > Order of runs is incorrect in GetStudyActivityList API in a scenario #4012
> [v2.0.8] Fixed issue #4012 study builder Active task custom scheduling GetStudyActivityList API 

- documentation/whats-new.md
- participant-datastore/consent-mgmt-module/consent-mgmt/pom.xml
- participant-datastore/enroll-mgmt-module/enroll-mgmt/pom.xml
- participant-datastore/user-mgmt-module/user-mgmt/pom.xml
- study-builder/fdahpStudyDesigner/pom.xml
- study-builder/fdahpStudyDesigner/src/main/resources/application.properties
- study-datastore/pom.xml
This PR has the fix to address CVE-2021-44228 in Apache Log4j 2.16.0. For details please refer this issue #4302
> [v2.0.9] Apache Log4j Security Vulnerabilities issue fix (master)

- participant-datastore/consent-mgmt-module/consent-mgmt/pom.xml
- participant-datastore/enroll-mgmt-module/enroll-mgmt/pom.xml
- participant-datastore/user-mgmt-module/user-mgmt/pom.xml
- study-builder/fdahpStudyDesigner/pom.xml
- study-builder/fdahpStudyDesigner/src/main/resources/application.properties
- study-datastore/pom.xml
This PR has the fix to address CVE-2021-44228 in Apache Log4j 2.16.0. For details please refer this issue #4302
> [v2.0.9] Apache Log4j Security Vulnerabilities issue fix (develop)
